### ISSUE TITLE
generate command failure

### ISSUE THREAD

**Issue by user-8472** [blacktop/ipsw#1]
Running under windows. First command I executed was:

```
 ./ipsw.exe generate
```

Which resulted in 
```
   ⨯ parsing table row failed  error=this is the table header
   ⨯ parsing table row failed  error=this is the table header
   ⨯ parsing table row failed  error=this is the table header
   ⨯ parsing table row failed  error=this is the table header
...
   ⨯ parsing table row failed  error=this is the table header
   ⨯ parsing table row failed  error=this is the table header
   ⨯ parsing table row failed  error=this is the table header
   ⨯ parsing table row failed  error=this is the table header
   ⨯ parsing table row failed  error=this is the table header
```

**Comment by blacktop** [comment]
So the `generate` cmd is something I should have commented out.  I initially thought I was going to have to crawl the iphonewiki's HTML tables to get device info and download URLs for the Beta Firmwares etc.  

So I was going to crawl the whole site and create a local database/expose a RESTful API to that data as a service that others could use to query. 

However, then I just started using ipsw.me's API (the non-beta firmwares) and got some momentum going with extracting parts of the ipsw files etc etc

For now I'm going to remove it, but will bring it back possible when I tackle beta-firmwares again

**Comment by user-8472** [comment]
Sounds good.
