### ISSUE TITLE
"ipsw download dev" command broke on iOS 15.5 beta 4 

### ISSUE THREAD

**Issue by homebinary** [blacktop/ipsw#104]
Output:
> $./ipsw download dev
> ? Please type your username: me@apple.com
> ? Please type your password: **********
> ? Choose a phone number to send the SMS code to: +1 • (•••) •••-••-11
> ? Please type your verification code: ******
> ? Choose a download type: beta
> ? Choose an OS version: iOS 15.5 beta 4
>    • Downloading               file=iOS_15_Beta_Profile.mobileconfig
>         7.12 KiB / 7.12 KiB [==========================================================| ✅  ]

json with product name "iOS 15.5 beta 4" have only one entry with file "iOS_15_Beta_Profile.mobileconfig" and type = "app"

**Comment by blacktop** [comment]
I noticed yesterday that Apple changed their website to no longer separate betas from releases so my web scraping is probably broken. Thanks for letting me know!

**Comment by blacktop** [comment]
should be good now, can you check and if good feel free to close the issue 👍

**Comment by homebinary** [comment]
Works now! Thanks!
