### ISSUE TITLE
download specific beta ipsw instead of all

### ISSUE THREAD

**Issue by highlystuff** [blacktop/ipsw#11]
Hello, I accidentally found this project, it really helps me a lot.I wonder if I could download only one specific beta ipsw for one specific device model, now it is asking me to download 16 ipsw files, which are too much, looking forward to your reply.

**Comment by blacktop** [comment]
I'm glad you are enjoying `ipsw` 😁 

Do you mean the `ipsw download beta` cmd or the `ipsw download ota` cmd?

Thanks!

**Comment by highlystuff** [comment]
I mean ipsw download beta.Can I download just one ipsw like 'ipsw download --device iPhone11,2 --build 16A366'?

**Comment by blacktop** [comment]
This was added in the latest release [v20.04.4](https://github.com/blacktop/ipsw/releases/tag/v20.04.4) thank you for using `ipsw` 😁
