### ISSUE TITLE
Crash while extracting files

### ISSUE THREAD

**Issue by mrlnc** [blacktop/ipsw#120]
Hi everybody! I'm fairly new to the tool, basically trying to extract all CountryBundle files from an OTA update. My understanding is that `ipsw` is exactly the right tool for the job :-) 

What I tried so far without success:

* `ipsw ota 1d848856bf7eaa330d77f9b01dc3b95b4d44c7a1.zip -o ios-ota`
  * only *lists* files, does not extract
* `ipsw ota 1d848856bf7eaa330d77f9b01dc3b95b4d44c7a1.zip -o ios-ota ".*"`
  * tries to extract files but looses directory structure, hence, skips many files as "duplicate"
* `ipsw ota 1d848856bf7eaa330d77f9b01dc3b95b4d44c7a1.zip -o ios-ota "System/Library/CountryBundles"`
  * looks good at first, but then `ipsw` crashes (see below).

I'm using this OTA update (15.4.1 -> 15.5): `https://updates.cdn-apple.com/2022FCSSpring/patches/012-07700/6172FFAF-C98C-482B-A2BF-913602FAB77C/com_apple_MobileAsset_SoftwareUpdate/1d848856bf7eaa330d77f9b01dc3b95b4d44c7a1.zip`

```
$ ipsw version
Version:  3.1.112 , BuildTime:  2022-06-20T02:59:10Z
```
## Crash log
```
ipsw ota 1d848856bf7eaa330d77f9b01dc3b95b4d44c7a1.zip -o ios-ota "System/Library/CountryBundles"
   • Extracting System/Library/CountryBundles...
      • Extracting -rw-r--r--	400 B	/System/Library/CountryBundles/iPhone/UnitedStates.bundle/Info.plist to 19F77__iPhone14,4/Info.plist
      • Extracting -rw-r--r--	1.9 kB	/System/Library/CountryBundles/iPhone/UnitedStates.bundle/carrier.plist to 19F77__iPhone14,4/carrier.plist
      • Extracting -rw-r--r--	597 B	/System/Library/CountryBundles/iPhone/UnitedStates.bundle/signatures/common.plist to 19F77__iPhone14,4/common.plist
panic: runtime error: slice bounds out of range [1181:1179]

goroutine 1 [running]:
github.com/blacktop/ipsw/pkg/ota.Extract.func1({0xc001a16720, 0x1e})
	github.com/blacktop/ipsw/pkg/ota/ota.go:442 +0x235
github.com/blacktop/ipsw/pkg/ota.parsePayload(0xc000458238, {0x7ff7bfeffbf1, 0x1d}, 0xc00126bb40)
	github.com/blacktop/ipsw/pkg/ota/ota.go:523 +0x482
github.com/blacktop/ipsw/pkg/ota.Extract({0x7ff7bfeffbb9?, 0x4c62f4a?}, {0x7ff7bfeffbf1, 0x1d}, {0x7ff7bfeffbe9, 0x7})
	github.com/blacktop/ipsw/pkg/ota/ota.go:439 +0x892
github.com/blacktop/ipsw/cmd/ipsw/cmd.glob..func65(0x553fd40?, {0xc0003e1d40, 0x2, 0x4?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/ota.go:87 +0x1f1
github.com/spf13/cobra.(*Command).execute(0x553fd40, {0xc0003e1d00, 0x4, 0x4})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x553ffc0)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:57 +0x25
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x17
```

**Comment by blacktop** [comment]
Wow thank you for such a detailed issue! I'll jump on this tomorrow and should have a fix out very soon.

**Comment by blacktop** [comment]
Can you tell me about the OS as well?

**Comment by mrlnc** [comment]
Sure, this is macOS 12.4 (21F79). I realized that the OTA update might not actually contain the files I'm looking for (so it's only listed in some index).

BTW, the crash happens after extracting the first few files:
```
./19F77__iPhone14,4
./19F77__iPhone14,4/carrier.plist
./19F77__iPhone14,4/common.plist
./19F77__iPhone14,4/Info.plist
```

**Comment by blacktop** [comment]
So I've got a good handle on the crash, however, due to the way OTAs work I added the ability to "stop" the extract once complete so you don't have to do an exhaustive search through the payloads looking for files of interest by first consuming the BOM file, however, these OTA you have chosen is a "partial" OTA meaning it doesn't actually contain a full file system, but just enough to patch an close version.  This means it only has the USA bundles, BUT the BOM lists the filesystem 😩 so that kills that optimization I think.

**Comment by blacktop** [comment]
I believe I have fixes all of these issues, please let me know if not and feel free to close if so.  Thanks again!!

**Comment by mrlnc** [comment]
Works great -- thanks!
