### ISSUE TITLE
 failed to load location PST8PDT

### ISSUE THREAD

**Issue by steam3d** [blacktop/ipsw#126]
I can't extract any  *.ipsw files. I tried the absolute path and relative. (Does not matter add or not symbol `"`)
```
.\ipsw.exe extract --dmg "iPhone14,5_15.5_19F77_Restore.ipsw"
⨯ failed to load location PST8PDT: The system cannot find the path specified.

.\ipsw.exe info "iPhone14,5_15.5_19F77_Restore.ipsw"

[IPSW Info]
===========
%!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)
```

- Windows 11
- ipsw.exe v3.1.120

**Comment by blacktop** [comment]
OOOOoo create an issue AND star the repo, you my friend know how to get your issue to the top of the priority list!

**Comment by blacktop** [comment]
I have cut a release with what I believe will fix the issue once it's done being built in Github's CI/CD it will be ready for you to try.  Thank you for reporting this issue and feel free to close this issue if it is indeed fixed.

**Comment by steam3d** [comment]
Everything fine now. Thx.
