### ISSUE TITLE
"ipsw info" Command Panics for AppleTV IPSWs

### ISSUE THREAD

**Issue by ewalkup** [blacktop/ipsw#13]
Not sure if it's meant to work, but it probably at least shouldn't panic.

Output (verbose does not give any more output):
```
[IPSW Info]
===========
%!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)
```

Files tested:
AppleTV3,1_8.4.3_12H876_Restore.ipsw   
AppleTV3,1_8.4.3_12H885_Restore.ipsw   
AppleTV3,1_8.4.3_12H903_Restore.ipsw

**Comment by blacktop** [comment]
Ah that IPSW is so old that the device tree went back to an Img3 file??

**Comment by ewalkup** [comment]
According to wikipedia, those are the 3 newest AppleTV builds, so maybe the device is just old. (Or maybe Apple is going back to Img3 files, which would be weird)

**Comment by blacktop** [comment]
Yeah it's an AppleTV 3rd gen which came out in 2012.

**Comment by blacktop** [comment]
Thank you for pointing this out to me, I definiately don't want ipsw (go's version of) seg faulting 😏 

I have pushed up support for Img3 device trees and now the output is:

```bash
[IPSW Info]
===========
Version        = 8.4.4
BuildVersion   = 12H903
OS Type        = 
FileSystem     = 
Devices
-------

AppleTV
 > AppleTV3,1_J33AP_12H903
   - KernelCache: [kernelcache.release.j33]
   - CPU: A5 (ARMv7), ID: s5l8942x
```

It has empty fields, but better than crashing ;)

```
brew update;brew upgrade
``` 

^ should pull down a fixed version (as soon as I cut the next release.
