### ISSUE TITLE
Can't Symbolicate MacOS Crash logs.

### ISSUE THREAD

**Issue by turnerrocks1** [blacktop/ipsw#135]
"*/Users/bootywarrior/Downloads/ipsw_3.1.123_macOS_arm64\ 2/ipsw symbolicate -d -u /Users/bootywarrior/Library/Logs/DiagnosticReports/Fi-2022-08-04-000004.ips /System/Library/dyld/dyld_shared_cache_arm64e
*"

"*⨯ unsupported crash log report version: 0*"

Pieces of the crash log itself
"-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

OS Version:            macOS 12.3.1 (21E258)
Report Version:        12" etc.etc.

**Comment by blacktop** [comment]
@turnerrocks1 would you mind sharing the log with me via discord or DM?

**Comment by turnerrocks1** [comment]
@blacktop sure thing ill share it tomorrow once I'm up :)
