### ISSUE TITLE
optional_output_path does not work for cmd `ipsw dyld split`

### ISSUE THREAD

**Issue by xuezhulian** [blacktop/ipsw#136]

**Comment by xuezhulian** [comment]
when i execute `ipsw dyld split /Users/yuencong/workplace/temp/dyld_shared_cache/iPhone14_6_15_6_19G71_Restore_ipsw/19G71__iPhone14,6/dyld_shared_cache_arm64e /Users/yuencong/Desktop/temp/symbols`
output is `   • Splitting dyld_shared_cache to /Users/yuencong/workplace/temp/dyld_shared_cache/iPhone14_6_15_6_19G71_Restore_ipsw/19G71__iPhone14,6
`

**Comment by blacktop** [comment]
Thank you for reporting!! I believe it is now fixed in the latest release.  Please feel free to close if the issue has been resolved 👍

**Comment by xuezhulian** [comment]
The problem has been solved, thank you very much.
