### ISSUE TITLE
Extract IPSW failed

### ISSUE THREAD

**Issue by ryanshummmm** [blacktop/ipsw#152]
Hi, I am using this command, then got this error, the new version ipsw [v3.1.182]

./ipsw extract -d iPhone15,3_16.0.1_20A371_Restore.ipsw

   • Extracting dyld_shared_cache
      • Created 098-09358-003.dmg
      • Mounting DMG 098-09358-003.dmg
         • Extracting dyld_shared_cache_arm64e to 20A371__iPhone15,3/dyld_shared_cache_arm64e
         • Extracting dyld_shared_cache_arm64e.01 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.01
         • Extracting dyld_shared_cache_arm64e.02 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.02
         • Extracting dyld_shared_cache_arm64e.03 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.03
         • Extracting dyld_shared_cache_arm64e.04 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.04
         • Extracting dyld_shared_cache_arm64e.05 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.05
         • Extracting dyld_shared_cache_arm64e.06 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.06
         • Extracting dyld_shared_cache_arm64e.07 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.07
         • Extracting dyld_shared_cache_arm64e.08 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.08
         • Extracting dyld_shared_cache_arm64e.09 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.09
         • Extracting dyld_shared_cache_arm64e.10 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.10
         • Extracting dyld_shared_cache_arm64e.11 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.11
         • Extracting dyld_shared_cache_arm64e.12 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.12
         • Extracting dyld_shared_cache_arm64e.13 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.13
         • Extracting dyld_shared_cache_arm64e.14 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.14
         • Extracting dyld_shared_cache_arm64e.15 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.15
         • Extracting dyld_shared_cache_arm64e.16 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.16
         • Extracting dyld_shared_cache_arm64e.17 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.17
         • Extracting dyld_shared_cache_arm64e.18 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.18
         • Extracting dyld_shared_cache_arm64e.19 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.19
         • Extracting dyld_shared_cache_arm64e.20 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.20
         • Extracting dyld_shared_cache_arm64e.21 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.21
         • Extracting dyld_shared_cache_arm64e.22 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.22
         • Extracting dyld_shared_cache_arm64e.23 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.23
         • Extracting dyld_shared_cache_arm64e.24 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.24
         • Extracting dyld_shared_cache_arm64e.25 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.25
         • Extracting dyld_shared_cache_arm64e.26 to 20A371__iPhone15,3/dyld_shared_cache_arm64e.26
         • Extracting dyld_shared_cache_arm64e.27.dylddata to 20A371__iPhone15,3/dyld_shared_cache_arm64e.27.dylddata
         • Extracting dyld_shared_cache_arm64e.28.dyldlinkedit to 20A371__iPhone15,3/dyld_shared_cache_arm64e.28.dyldlinkedit
      • Unmounting DMG 098-09358-003.dmg

failed to extract dyld_shared_cache(s) from IPSW: failed to copy /tmp/ios/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e.28.dyldlinkedit to 20A371__iPhone15,3/dyld_shared_cache_arm64e.28.dyldlinkedit: failed to open '/tmp/ios/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e.28.dyldlinkedit': open /tmp/ios/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e.28.dyldlinkedit: input/output error

**Comment by ryanshummmm** [comment]
Model Name: Mac mini
      Model Identifier: Macmini9,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 6723.140.2
      OS Loader Version: 6723.140.2

using [ipsw_3.1.182_macOS_x86_64.tar.gz]

**Comment by blacktop** [comment]
That looks like it tried to unmount the DMG before it was done copying the files out. Very strange. I'll take a look at the code.

**Comment by ryanshummmm** [comment]
@blacktop hi, may I know what is the cause root?
I used **Version:  3.0.85 , BuildTime:  2021-10-09T06:26:00Z** before, and got this

   • Extracting dyld_shared_cache
      • Mounting DMG
      • Unmounting DMG
Error: failed to extract dyld_shared_cache: failed to find dyld_shared_cache in ipsw: iPhone_4.7_P3_16.0_20A362_Restore.ipsw

so I changed to the newest version mentioned above.
I noticed ipsw_3.1.188_macOS_arm64 is been released, but still got sth like

failed to extract dyld_shared_cache(s) from IPSW: failed to copy /tmp/ios/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64e.28.dyldlinkedit to

**Comment by ryanshummmm** [comment]
this error seems just showed up on IOS 16 or above

**Comment by blacktop** [comment]
@ryanshummmm is there anything special about the way you are running/copying these files?  There's another issue where the copying was failing here #109 where they were extracting to a share drive?

**Comment by blacktop** [comment]
So I initially thought it looked like a race condition from the log output, but all it is saying is that it was able to extract ALL the DSC subcaches until it tried `dyld_shared_cache_arm64e.28.dyldlinkedit` and that failed to open for some reason and that threw an error that caused the extraction to fail.

**Comment by blacktop** [comment]
I have no idea why that would fail but the others would succeed.  Maybe antivirus or something was "scanning" it and that prevented it from being copied?  You could also unzip the IPSW and try and mount that `098-09358-003.dmg` and manually copy the DSC out and see if that works?

**Comment by ryanshummmm** [comment]
@blacktop I tried to copy them from the mounted dmg, looks like is the file problem..
<img width="1362" alt="截屏2022-09-28 下午2 12 32" src="https://user-images.githubusercontent.com/106363454/192701477-a0b8172c-d4f9-4546-b55f-97b3c2441075.png">

cp: ./dyld_shared_cache_arm64.28.dyldlinkedit: Input/output error
cp: ./dyld_shared_cache_arm64.40.dyldlinkedit: Input/output error
cp: ./dyld_shared_cache_arm64.symbols: Input/output error

**Comment by pwmoore** [comment]
So I have ran into this problem, although it may be unrelated to what @ryanshummmm is seeing here. I wanted to add this information though in hopes it will help.

I'm trying to extract the 16.0 DSCs on a Linux machine, so I'm using `apfs-fuse` and a custom Python script, but I was wanting to switch to using `ipsw`. However, I ran into the same problem with extracting these files on my Linux machine with both my script and with `ipsw`. 

After doing some digging, it seems like the files that @ryanshummmm mentioned are compressed with a new form of compression [LZBITMAP](https://developer.apple.com/documentation/compression/compression_algorithm/compression_lzbitmap). If I mount the DMG with `apfs-fuse`, you can see that it fails to report the correct sizes of those files: 

```
-rwxr-xr-x 1 root 80   16 Jan  1  1970 dyld_shared_cache_arm64e.28.dyldlinkedit
-rwxr-xr-x 1 root 80   16 Jan  1  1970 dyld_shared_cache_arm64e.44.dyldlinkedit
-rwxr-xr-x 1 root 80   16 Jan  1  1970 dyld_shared_cache_arm64e.symbols
```

I've done a little reverse engineering of the LZBITMAP stuff, and I've gotten a hacked up copy of `apfs-fuse` at least recognizing the correct file sizes, but reversing the decompression algorithm would be a lot more work. I'm not sure if `ipsw` uses `apfs-fuse` on macOS or not, so again, this may not be relevant to this particular issue. I still need to report this to `apfs-fuse`. They are the experts here, and ideally they would be the ones to add support for this new type of compression.

**Comment by blacktop** [comment]
@ryanshummmm I'm confused by that last comment as it seems to suggest that it's not an `ipsw` problem at all but something wrong with that IPSW or your host?

**Comment by blacktop** [comment]
@pwmoore on macOS it just execs to hdiutil so will always work.  In docker I use apfs-fuse on linux I'm actually not sure that that cmd should even be exposed?  I guess it is because of the docker version, so if you had apfs-fuse installed it would use that.  I have noticed apfs-fuse stopped working on iOS16 and I also have another project that is a pure Go APFS parser that was experiencing a similar issue to apfs-fuse here https://github.com/blacktop/go-apfs that will become the default non-darwin solution in `ipsw` once I feel it's non-beta, but I REALLY appreciate your insight as I haven't had time to dig into why my APFS parser was having issues w/ DSCs so I'll take a look and see if I can fix the issue in go-apfs

**Comment by pwmoore** [comment]
@blacktop Yeah no problem, happy to help! The LZBITMAP stuff is part of `libcompression` and like the other decompression codecs there is a matching `lzbitmap_decompress_buffer()` function, but it's all vectorized instructions that look like a PITA to RE much less implement cross platform.😅 It would be lovely if Apple open sources it like LZFSE.

**Comment by blacktop** [comment]
Yeah researching it now and it seems like it's their secret sauce, I say it mentioned in the Metal framework too.  Prob no reason to opensource unless the devs fought for it to be?  It being closed source will prevent things like go-apfs and apfs-fuse from ever working though 😩 So we are going to have to RE it.... LET"S GO!!!!! 😏

**Comment by blacktop** [comment]
@pwmoore just cracked it open in IDA and.... 🤮

**Comment by pwmoore** [comment]
😂😂😂 I'm glad I'm not the only one who had that reaction. My first thought "This will be easy peasy, I'm good at reversing, I... dear god in heaven... why are my eyes bleeding?"

**Comment by ryanshummmm** [comment]
@blacktop hi, me again, I just upgrade the os version to the new one, and the problem has been solved, but after extraction, the split got some error, can you take a look for the new issue

• Splitting dyld_shared_cache to /system_framework_collect/20A362_iPhone10,1/20A362__iPhone10,1_4

Error: stat failed for dyld shared cache at /system_framework_collect/20A362_iPhone10,1/20A362__iPhone10,1_4/dyld_shared_cache_arm64.1
Usage:
  ipsw dyld split <dyld_shared_cache> <optional_output_path> [flags
Flags:
  -b, --build string     Cache build
  -c, --cache            Build XCode device support cache
  -h, --help             help for split
  -v, --version string   Cache version
  -x, --xcode string     Path to Xcode.app

Global Flags:
      --color           colorize output
      --config string   config file (default is $HOME/.ipsw.yaml)
  -V, --verbose         verbose output

   ⨯ failed to run dsc_extract
idsc_extractor /system_framework_collect/20A362_iPhone10,1/20A362__iPhone10,1_4/dyld_shared_cache_arm64 failed

**Comment by ryanshummmm** [comment]
my command is :
./ipsw dyld split /system_framework_collect/20A362_iPhone10,1/20A362__iPhone10,1_4/dyld_shared_cache_arm64 ./ipsw dyld split /system_framework_collect/20A362_iPhone10,1/20A362__iPhone10,1_4

**Comment by blacktop** [comment]
Ya that error is confusing and I need to fix it. That command requires Xcode to be installed or somewhere on your macOS system

**Comment by ryanshummmm** [comment]
true hah, i updated XCODE and it works, thx
