### ISSUE TITLE
ipsw.exe blocked by windows defender (Smart app control)

### ISSUE THREAD

**Issue by A-Metwally** [blacktop/ipsw#154]
OS version: Windows 11 Pro, 22H2, build 22621.674
ipsw version: 3.1.189
![image](https://user-images.githubusercontent.com/54812806/195885775-aef63e5e-187a-42a1-9e6b-e71a9f6a836e.png)

**Comment by blacktop** [comment]
question would you also be willing to use chocolatey or do you prefer scoops?

**Comment by A-Metwally** [comment]
> would you also be willing to use chocolatey or do you prefer scoops?

I do prefer scoop but I would use any package manager that gives me easy access to your great software.


idk how popular chocolatey is, and I know it’s your decision whether you are willing to maintain another source for your package or even migrate from scoop, but if your investigation shows that this issue is scoop specific, i’ll report it there.
For now, I turned off Smart app control, it feels quite premature at the moment, blocking some parts of MS office and VS Code installers was the funniest.

**Comment by blacktop** [comment]
I don't see any fields in the manifests that would contain an identity or signature.  I did find this - https://github.com/ScoopInstaller/Scoop/wiki/Antivirus-and-Anti-Malware-Problems

**Comment by blacktop** [comment]
I'm going to support scoops and choclatey and hopefully Windows Defender figures out how it's issues?

**Comment by blacktop** [comment]
I can't support chocolatey until they create a macOS client sadly, however, I hope the scope issue has or will resolve soon
