### ISSUE TITLE
ipsw dyld split fails on Docker for some iOS versions (e.g.,12.0)

### ISSUE THREAD

**Issue by ahmed24khaled** [blacktop/ipsw#156]
Hello,
I'm trying to extract DSC from dyld_shared_cache_arm64e for some iOS versions using docker, but it's not working as expected (and it works perfectly for some versions).

Below the executed command and the output error for iOS 12.0 (iPhone11,2) as example:

`$ docker run --init -it --rm  -v $(pwd):/data  blacktop/ipsw:latest -V dyld split dyld_shared_cache_arm64e -a --output /data/`

```
• Parsing Cache             cache=dyld_shared_cache_arm64e
      21m11s [------------------------------------------------------------------------------| 0 % ]
Usage:
  ipsw dyld split <dyld_shared_cache> <optional_output_path> [flags]

Flags:
  -a, --all             Split ALL dylibs
      --force           Overwrite existing extracted dylib(s)
  -h, --help            help for split
      --output string   Directory to extract the dylib(s) (default "o")

Global Flags:
      --color           colorize output
      --config string   config file (default is $HOME/.ipsw.yaml)
  -V, --verbose         verbose output

   ⨯ failed to rebase macho via cache slide info: address 0x180030000 not within any mapping's address range
```
   
   As you can see I got '⨯ failed to rebase macho via cache slide info: address 0x180030000 not within any mapping's address range'
   
   The ipsw file: 
     {
    "identifier": "iPhone11,2",
    "version": "12.0",
    "buildid": "16A366",
    "url": "http://updates-http.cdn-apple.com/2018FallFCS/fullrestores/091-65197/11B6401E-AC8E-11E8-8834-D2D1B8DB0242/iPhone11,2_12.0_16A366_Restore.ipsw",
    "releasedate": "2018-09-17T17:06:51Z",
    "uploaddate": "2018-08-30T20:00:50Z",
    "signed": false
  }

   Any advice please ?
   Thank you

**Comment by blacktop** [comment]
Does it work with higher versions of iOS?

`ipsw` is mostly meant to work on the LATEST version of iOS.  I'd like to support ALL iOS versions, however, I think when I started building `ipsw` it was iOS 13 or 14? So I don't think I've ever tested on older versions than that.

**Comment by ahmed24khaled** [comment]
Yes it works with higher versions (I have checked on few versions).
I see that the error `failed to rebase macho via cache slide info: address 0x180030000 not within any mapping's address range` comes from this function https://github.com/blacktop/ipsw/blob/master/cmd/ipsw/cmd/dyld/dyld_split_other.go#L129

I commented out this line and relaunch the command locally and it worked. I found all binaries files extracted.
In this case what is the purpose of rebaseMachO(f, fname) ? and if I remove this line what is the impact on the split on other versions ?

Last question: comparing the size of total extracted files to other tool like [DyldExtractor](https://github.com/arandomdev/DyldExtractor) I see a big difference. e.g, for iOS 14.0 (18A373) arm64e , total size after split is 6,55 GB however it is 2,74 GB using DyldExtractor. 
Any advice ?

Thank you.

**Comment by ahmed24khaled** [comment]
@blacktop any updates on this issue please ?

**Comment by blacktop** [comment]
It should be fixed now.

DyldExtractor goes beyond what `ipsw` currently does in that it also moves the ObjC runtime info and fixes up stubs/GOT

`ipsw` will do that soon-ish, but for now DyldExtractor is a better splitter. 

I have made some improvements to the splits that `ipsw` does that might change the outputed MachO's sizes.

Please close the issue if the fix is sufficient.  Thanks
