### ISSUE TITLE
ipsw extract dyld error 

### ISSUE THREAD

**Issue by guoziyuan** [blacktop/ipsw#157]
ios 16.1, build  20B82
ipsw version 3.1.193
failed to extract dyld_shared_cache(s) from IPSW: failed to copy /tmp/078-65022-105.dmg.mount/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64.28.dyldlinkedit to 20B82__iPhone10,1_4/dyld_shared_cache_arm64.28.dyldlinkedit: failed to open '/tmp/078-65022-105.dmg.mount/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64.28.dyldlinkedit': open /tmp/078-65022-105.dmg.mount/System/Library/Caches/com.apple.dyld/dyld_shared_cache_arm64.28.dyldlinkedit: input/output error

**Comment by blacktop** [comment]
This sounds like #152 can you please take a look and see if any of that helps you?

**Comment by guoziyuan** [comment]
It works after I update the xcode

**Comment by sraka1** [comment]
@blacktop I'm also having issues with parsing the .dmg files in .ipsw's that are iOS >16. I'm on MacOS Monterey (12.5.1) and have Xcode 14.2. Based on https://developer.apple.com/documentation/compression/compression_algorithm/compression_lzbitmap?changes=latest_major, LZBITMAP compression _should_ be supported...any thoughts?

**Comment by blacktop** [comment]
My guess is that macOS 12.x doesn't support the new lzbitmap compression
