### ISSUE TITLE
ipsw dyld parsing takes up to 70gb of ram

### ISSUE THREAD

**Issue by qu0dy** [blacktop/ipsw#163]
Hi,

I have tried to use `ipsw dyld a2s /System/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_arm64e` on MacOS 13.1 Beta and during execution, the process takes up to 70gb of RAM. In contrast it works for x86_64 cache without taking all the RAM.

**Comment by blacktop** [comment]
There are some commands that parse dylibs (the dyld disass, dyld a2s and a few others) and extract a TON of info to extract every possible symbol, metadata of interest and if you ask for something that might depend on a LOT of other dylibs I could see it loading TOO much info etc

It's VERY strange to me that x86_64 doesn't have the same issue?  I'd like to debug if you could tell me the OS version of the DSC and the address you searched for?

I do need to do some perf improvements on some of the more intense cmds and let go of structs I don't really need etc maybe a LRU cache etc

**Comment by blacktop** [comment]
On second thought it does make sense x86 would be different because `ipsw` does a fair bit of disassembly analysis to find more info and to parse stubs etc and it can't do that on x86 as the disassembler only supports ARM64

**Comment by qu0dy** [comment]
> sw_vers
```
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C5050e
```

> you could use any address and `a2s` for `dyld_shared_cache_arm64e` will reach 70-80gb at least

**Comment by blacktop** [comment]
One thing I could do is only look at public/private syms and then do deeper dives if the user wants to etc

**Comment by qu0dy** [comment]
@blacktop also `ipsw dyld a2f /System/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_arm64e -j -i /tmp/inp` gets out of memory (70+gb), `0x182d57920` as an example pointer. Without `-i` flag, with the same pointer it works correctly.

**Comment by qu0dy** [comment]
> sw_vers
```
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C5059b
```

On newer MacOS Ventura Beta 4 is works without out-of-memory issues.

**Comment by blacktop** [comment]
Interesting!

**Comment by blacktop** [comment]
that's ARM64?

**Comment by qu0dy** [comment]
Yes, it's arm64.

**Comment by blacktop** [comment]
Please try the latest release, I believe I might have pin pointed the issue causing the RAM to spin out of control.  I still need to get it lower, but I shouldn't be bad anymore. 

If satisfied, please feel free to close the issue.
