### ISSUE TITLE
`ipsw extract --dyld` output doesn't have _arm64 (etc) arch declaration at the end

### ISSUE THREAD

**Issue by KritantaDev** [blacktop/ipsw#18]
minor thing, just creates an extra step for others outside rn to do

**Comment by blacktop** [comment]
that's a good point, when every I tried to process a ton of dsc, I'd always have to glob for 64 and 64e caches so I thought I might as well just call them all same and the folder they are in informs you of what arch it is if you are very familiar with the ipsw spec etc, but i guess it makes more sense to just write out the file as it exists in the DMG

**Comment by blacktop** [comment]
I believe I no longer am cutting off the end of the dsc name
