### ISSUE TITLE
Feature request: Extract kernelcache from remote ipsw

### ISSUE THREAD

**Issue by pwnee** [blacktop/ipsw#184]
Hello, thanks for the awesome tool!

As you might already know, https://github.com/tihmstar/partialZipBrowser is able to download just the kernelcache (or any other single file) from an ipsw url. But this kernelcache is not decompressed. I thought `ipsw` is the right tool to ask for this feature :) In my use case; I usually just need the kernelcache files, which are <100MB but I need to download 6-7 GB sized ipsw's.

Thanks in advance.

**Comment by blacktop** [comment]
If you don't already have the URL 

https://blacktop.github.io/ipsw/docs/guides/download/#download-ipsw---kernel

If you do

`ipsw extract --kernel --remote URL`

**Comment by pwnee** [comment]
ah! I thought I've checked out all related options

**Comment by pwnee** [comment]
There is a little bug in remote kernelcache extraction mechanism: The folder(s) are not created automatically, thus extraction fails with `no such file` error. Once you create the folders yourself, extraction succeeds:

```sh
% ipsw extract -k -r https://updates.cdn-apple.com/2023WinterFCS/fullrestores/032-49723/F2250E1E-7ADB-4CD6-B95E-1BF4DFBD5E81/iPhone13,1_16.3.1_20D67_Restore.ipsw
   • Extracting remote kernelcache
   ⨯ failed to extract kernelcache from remote IPSW: failed to write kernelcache: open 20D67__iPhone13,1/20D67__iPhone13,1/kernelcache.release.iPhone13,1: no such file or directory
% mkdir -p 20D67__iPhone13,1/20D67__iPhone13,1/
% ipsw extract -k -r https://updates.cdn-apple.com/2023WinterFCS/fullrestores/032-49723/F2250E1E-7ADB-4CD6-B95E-1BF4DFBD5E81/iPhone13,1_16.3.1_20D67_Restore.ipsw
   • Extracting remote kernelcache
      • Writing 20D67__iPhone13,1/20D67__iPhone13,1/kernelcache.release.iPhone13,1
```

**Comment by pwnee** [comment]
There is a little bug in remote kernelcache extraction mechanism: The folder(s) are not created automatically, thus extraction fails with `no such file` error. Once you create the folders yourself, extraction succeeds:

```sh
% ipsw extract -k -r https://updates.cdn-apple.com/2023WinterFCS/fullrestores/032-49723/F2250E1E-7ADB-4CD6-B95E-1BF4DFBD5E81/iPhone13,1_16.3.1_20D67_Restore.ipsw
   • Extracting remote kernelcache
   ⨯ failed to extract kernelcache from remote IPSW: failed to write kernelcache: open 20D67__iPhone13,1/20D67__iPhone13,1/kernelcache.release.iPhone13,1: no such file or directory
% mkdir -p 20D67__iPhone13,1/20D67__iPhone13,1/
% ipsw extract -k -r https://updates.cdn-apple.com/2023WinterFCS/fullrestores/032-49723/F2250E1E-7ADB-4CD6-B95E-1BF4DFBD5E81/iPhone13,1_16.3.1_20D67_Restore.ipsw
   • Extracting remote kernelcache
      • Writing 20D67__iPhone13,1/20D67__iPhone13,1/kernelcache.release.iPhone13,1
```

**Comment by blacktop** [comment]
Thank you for letting me know! I am releasing a fix now.  Please check the latest release when it's done being pushed out.

Also just FYI another way to do that cmd is:

```bash
ipsw download ipsw --kernel --version 16.3.1 --device iPhone13,1
```

**Comment by blacktop** [comment]
feel free to re-close the issue if it is fixed.

**Comment by pwnee** [comment]
Thanks, it works fine now
