### ISSUE TITLE
ipsw dyld split <file> fails when file is a symlink

### ISSUE THREAD

**Issue by KritantaDev** [blacktop/ipsw#19]
felt this was worth filing as `ipsw` itself creates symlinks when providing the extracted dsc for `iPhone10,3,iPhone10,6_13.7_17H35_Restore.ipsw` (which is weird behavior but, seems to function?)

**Comment by blacktop** [comment]
thanks for letting me know, I started doing to symlinks to prevent creating copies of the dsc and wasting space, with the DEVICE_BOARD_BUILD folder names, but I should just standardize on the ipsw file name string as a folder name instead style 😞

**Comment by blacktop** [comment]
i have a NEW folder/file naming scheme:

```bash
❯ tree test-caches/18F72__iPad13,4_5_6_7_8_9_10_11 
test-caches/18F72__iPad13,4_5_6_7_8_9_10_11
└── kernelcache.release.iPad13,4_5_6_7_8_9_10_11
```

no more sym links or copying kernels in multi folders

hopefully people like it
