### ISSUE TITLE
Github pages device list page broken?

### ISSUE THREAD

**Issue by daluu** [blacktop/ipsw#190]
I get a 404 not found type page loading when viewing this page: https://blacktop.github.io/ipsw/docs/commands/device-list/. It used to contain list of iOS devices and their info.

Was the page purposely removed sometime, or did something break in the visual rendering of the content? I looked over the github pages branch and could not find any specific change referencing removal of said content. The other more recent commits have a compiled version of the page content such that I'm unaware if it is expected to have the device data or not.

**Comment by blacktop** [comment]
Ah I did notice people were getting a 404 but I didn't know what page was causing it!

It was moved to here - https://blacktop.github.io/ipsw/docs/guides/device_list

FYI there's a more complete list [here](https://github.com/blacktop/ipsw/raw/master/pkg/info/data/ipsw_db.json)
