### ISSUE TITLE
Tapi-analyze function 

### ISSUE THREAD

**Issue by lilili87222** [blacktop/ipsw#195]
May you add function like tapi-analyze?

**Comment by blacktop** [comment]
what part of that tool is valuable to you?

**Comment by lilili87222** [comment]
may you add function like this output?or how to do this
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/tapi-analyze --app-info-output=- ./test.app/test

**Comment by lilili87222** [comment]
to view import and dependences of a macho

**Comment by lilili87222** [comment]
close
