### ISSUE TITLE
Will this allow me to dump a restorable firmware file? Specifically from a HomePod, A8 SoC based...

### ISSUE THREAD

**Issue by UnbendableStraw** [blacktop/ipsw#201]
I was curious if this tool would theoretically allow me to dump restorable firmware from a working first generation Apple HomePod? This is so I can then use this image to restore bricked HomePods, since Apple hasn't made the firmware public like everything else...

A1639 HomePod is A8 based!

**Comment by blacktop** [comment]
I have not looked into creating IPSWs yet as I thought they would need to be properly signed by Apple to be installed on actual devices?
