### ISSUE TITLE
add more commands for iOS 15

### ISSUE THREAD

**Issue by uaex** [blacktop/ipsw#23]
I can not use `ipsw dyld symaddr --image <image> <dscpath> <symbol>` because iOS 15 beta has new dsc format.
Can you add command to extract dyld_shared_cache(like dsc_extractor) and lookup symbols?

like:
`ipsw extract --dsc < dscpath> <outputdir>`
`ipsw macho <image> -symaddr <symbol>`

**Comment by blacktop** [comment]
you could run: 

```bash
$ ipsw dyld split <dsc_path> <outoput_path>
$ ipsw macho <outoput_path>/System/Library/Frameworks/WebKit.framework/WebKit --symbols
```

**Comment by uaex** [comment]
> you could run:
> 
> ```shell
> $ ipsw dyld split <dsc_path> <output_path>
> $ ipsw macho <output_path>/System/Library/Frameworks/WebKit.framework/WebKit --symbols | grep <symbol>
> ```
> 
>  > **NOTE:** requires Xcode 13beta installed

**Comment by uaex** [comment]
thks
