### ISSUE TITLE
`ipswd_3.1.331_linux_x86_64.pkg.tar.zst` fails to install `ipswd: /lib exists in filesystem (owned by filesystem)`

### ISSUE THREAD

**Issue by OldWorldOrdr** [blacktop/ipsw#231]
This happens because /lib is a symlink to /usr/lib, and pacman assumes you want to replace the symlink.  The fix is to move all files in /lib to /usr/lib.

**Comment by blacktop** [comment]
pushed out latest version w/ possible fix.

please let me know if this helps.

thank you for letting me know!

I'm not a linux power user so am not 💯 sure how to make pkgs that properly install/start daemons.

👍

**Comment by OldWorldOrdr** [comment]
IIRC systemd expects merged /usr (/bin, /lib, and /sbin are symlinks to their /usr counterparts) and doesn't even support other configurations.

**Comment by OldWorldOrdr** [comment]
issue was fixed
