### ISSUE TITLE
Failed to extract dyld_shared_cache when run in GitHub Action

### ISSUE THREAD

**Issue by frankschlegel** [blacktop/ipsw#243]
I'm trying to extract the `dyld_shared_cache` from an IPSW as part of a GitHub Actions workflow. 

Until recently, this worked fine. But in the latest version, it fails with the following message:

>    • Extracting dyld_shared_cache
>         • Mounting DMG 096-04666-078.dmg
>    ⨯ failed to find dyld_shared_cache(s) in DMG: 096-04666-078.dmg

I traced the message to [this line](https://github.com/blacktop/ipsw/blob/37c02111eecd864f1b0e1f3b146f83124d31bb2a/pkg/dyld/extract.go#L124) in [pkg/dyld/extract.go](https://github.com/blacktop/ipsw/blob/master/pkg/dyld/extract.go).
Some recent changes seem to have broken the `extract` command – at least on Linux (GitHub Actions). When run locally on my Mac, everything works as expected.

I'm using an older version of ipsw in my workflow now (v3.1.300), which fixes the issue for now.

**Comment by blacktop** [comment]
Thank you for reporting! ❤️ It should be fixed in the next release.  Once it's out please let me know if the issue persists.

**Comment by blacktop** [comment]
just tested via docker and it worked so it's looking good

**Comment by frankschlegel** [comment]
Yes, it works now. Thanks for the very fast response! ❤️
