### ISSUE TITLE
Xcode 15 runtimes

### ISSUE THREAD

**Issue by withzombies** [blacktop/ipsw#247]
For the Xcode 15 release, Apple has separated out the runtimes for each platform (making the Xcode download only 2.2GB!).

Several additional files need to be downloaded to support offline iOS use:
* iOS_17_beta_Simulator_Runtime.dmg
* DeveloperDiskImage.dmg

Could ipsw learn how to download these?

**Comment by blacktop** [comment]
I assume this is for offline use (as Xcode downloads all these when you first boot it)

I'll def take a look at supporting offline use downloads 👍

**Comment by blacktop** [comment]
check out the new `ipsw download xcode` cmd and let me know what you think ;)

**Comment by withzombies** [comment]
It seems to work well!

Two things:
* It doesn't show up in the `ipsw download --help` menu
* The simulators are listed in chronological order under `ipsw download xcode --sim` and it would be best if it were reverse chronological

**Comment by blacktop** [comment]
done, should be in next release
