### ISSUE TITLE
ipsw dyld extract -> ida crash

### ISSUE THREAD

**Issue by 0xsunsama** [blacktop/ipsw#250]
iPhone: 20E247__iPhone10,3_6 
ipsw dyld extract --stubs --objc dyld_shared_cache_arm64 WebKit ,this is ok.
ida loading Webkit , 100% crash.
[crash.log](https://github.com/blacktop/ipsw/files/11731752/crash.log)

**Comment by blacktop** [comment]
I apologize, I'm aware that there are some issue's with how I'm extracting dylibs from the DSC and plan to revisit and finish it, but can't promise a timeline now.
