### ISSUE TITLE
Feature Request: Only list download URLs

### ISSUE THREAD

**Issue by raymontag** [blacktop/ipsw#263]
`ipsw -V download appledb --os iOS --kernel --device iPhone14,4` will give me a list of URLs that ipsw is attempting to download before prompting me if I want to download x IPSWs. It would be nice to have an option to just list those URLs without a prompt or something so that I can process the URLs myself easily.

**Comment by blacktop** [comment]
Added `--urls` flag.  I will prob cut a new release tomorrow or the day after.  Thanks for the issue! 👍

**Comment by blacktop** [comment]
check latest release and feel free to close if satisfied

**Comment by raymontag** [comment]
Very cool, thanks mate!
