### ISSUE TITLE
Local git clone for appledb backend

### ISSUE THREAD

**Issue by torarnv** [blacktop/ipsw#264]
The appledb backend queries the GitHub repo of appledb, and easily ends up being rate limited. There doesn’t seem to be any option to pass a GitHub token either, like for the git downloader, but even that would quickly be rate limited too.

As all the appledb downloader is doing is iterating and reading the files of the repo, perhaps the logic can be replaced with a local clone of the repo in /tmp that is fetched when needed. This would presumably fix the rate limiting issue.

**Comment by blacktop** [comment]
Adding new `--api` flag and will also check for `GITHUB_TOKEN`/`GITHUB_API_TOKEN` env vars

**Comment by blacktop** [comment]
I will cut a new release prob tomorrow or the day after for you to test. Thanks for the issue! 👍

**Comment by blacktop** [comment]
Also adding a `--local` flag to use local git repo instead of API

**Comment by blacktop** [comment]
created a release, let me know what you think

**Comment by blacktop** [comment]
pushing a fix now along w/ a NEW `--latest` flag

**Comment by torarnv** [comment]
Awesome, seems to work well! Could perhaps even be the default?

**Comment by blacktop** [comment]
true, it's SO much faster than using the APIs (but that's mostly due to the way the applied people decided to design their JSON/files etc.  but I think making local the default makes a lot of sense

**Comment by blacktop** [comment]
default is local repo now, should be in next release
