### ISSUE TITLE
feature request: add `dyld uuid` command

### ISSUE THREAD

**Issue by doronz88** [blacktop/ipsw#27]
It would be really nice if `ipsw` could extract all UUIDs of the different images from the dyld_shared_cache_arm64*. Maybe also include several export functions? like into json?

I'm planning to implement a feature for [pymobiledevice3](https://github.com/doronz88/pymobiledevice3) which allows to see which images are loaded to currently running process. The only problem is that the `pymobiledevice3 developer dvt core-profile-session stackshot` currently gives all the loaded images as UUIDs and not by their names.

**Comment by blacktop** [comment]
I've added a `--json` flag to `ipsw dyld info` *(the long term plan was always to expose a RESTful API from `ipsw` so others could query it from other langs/platforms)*

```bash
ipsw  dyld info test-caches/iPhone12,1_N104AP_19A5261w/dyld_shared_cache_arm64e --json | jq .
```

```json
{
  "magic": "dyld_v1  arm64e\u0000",
  "uuid": "F5097CDC-9388-382F-8D13-AAE184497224",
  "platform": "iOS",
  "max_slide": 57638912,
  "mappings": [
    {
      "Name": "__TEXT",
      "Address": 6442450944,
      "Size": 1339211776,
      "FileOffset": 0,
      "SlideInfoOffset": 0,
      "SlideInfoSize": 0,
      "Flags": 0,
      "MaxProt": 5,
      "InitProt": 5
    },
    {
      "Name": "__DATA_CONST",
      "Address": 7815217152,
      "Size": 49840128,
      "FileOffset": 1339211776,
      "SlideInfoOffset": 1548271616,
      "SlideInfoSize": 32768,
      "Flags": 4,
      "MaxProt": 3,
      "InitProt": 1
    },
<SNIP>
  ],
  "dylibs": [
    {
      "name": "/usr/lib/system/libdispatch.dylib",
      "version": "1319.0.0",
      "uuid": "FFA2D8B7-6140-3795-9FAD-8615E27E5BD2"
    },
    {
      "index": 1,
      "name": "/usr/lib/system/libdyld.dylib",
      "version": "1.0.0",
      "uuid": "0943406A-75D8-3BA2-AEAC-5CA47E119B45"
    },
    {
      "index": 2,
      "name": "/usr/lib/libicucore.A.dylib",
      "version": "68.2.0",
      "uuid": "9AEA2189-8B39-3F26-835D-947D82717FA0"
    },
    {
      "index": 3,
      "name": "/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation",
      "version": "1835.100.0",
      "uuid": "4B514B9D-2B35-32CA-A93F-481D3A903177"
    },
    <SNIP>
```

**Comment by doronz88** [comment]
This is so awsome! thank you :)
Also I think that `--json` data should be the same I see without the json flag, since you usually would assume an optional output flag doesn't add data for viewing. Since this flag is much more than output change it at least would deserve better documentation in the help message.

Also, I think the output should be indented so people can view it nicely (especially if data is not available otherwise).

And the RESTful api sounds amazing!

**Comment by doronz88** [comment]
I've just noticed that when running `ipsw dyld -l -V` it gives out more information and includes the loading addresses. It would be nice to have that also included in the json format

**Comment by blacktop** [comment]
Added load address to JSON and am now respecting the other flags in the `dyld info` cmd.  It's not a perfect reproduction of the non-json output as that will require more careful thought and a refactor of my "formatter" code (because now there is complex logic there to avoid showing info that is all zeros (removed in a newer version of dyld_header_format etc)

So we can leave this issue open as a reminder to me to REALLY add JSON output for every cmd in the path to a RESTful API.

**Comment by blacktop** [comment]
> Also, I think the output should be indented so people can view it nicely (especially if data is not available otherwise).

So I always felt like if someone wanted to read the JSON you'd run it through `jq` otherwise you would want the JSON minimized to minimize the overall size of the data to then be consumed somewhere else?  Do you disagree?  I know a lot of your tools output pretty JSON, but I usually don't read LONG json myself and if I do I use `jq`

**Comment by doronz88** [comment]
Usually I want my tools to be as self-contained as possible, meaning the users don't require any extra binaries for their usage. I chose to output as JSON so it's easy to query from other programs and also because it's pretty readable as-is and doesn't require too much effort for formatting the best output. I think both approaches are just as fine as long as the tool is consistent in their usage for every command - so it's fine as it is now :)

Also, I started implementing the feature I discussed earlier and just came to the realization the UUID of the images as seen in their LOAD command isn't the one I get from getting the stackshot. I used your `Dyld.bt` to debug it and surprise:

As it turns out, all the binaries from the system partition (even non-dylibs such as `/sbin/launchd` and eveyone else) are also found in the DSC but in another region that isn't yet explored. The UUID I get when querying the stackshot from the device is the one found there and is different from the mach-o's UUID as it appears in the DSC LOAD command. I'm currently still trying to figure out how to parse this section.

BTW, this also means that when XCode tries to symbolicate dumps from the device it will use these other-UUIDs.

**Comment by blacktop** [comment]
Wow! I'm VERY interested in what you find. There is still this mysterious NEW data structure in the dsc that I cant figure out. In Dyld.bt I refer to it as unknown10. Maybe it's somehow related??

**Comment by blacktop** [comment]
There is also a new DriverKit dsc that I haven't looked at yet. Maybe take a look at that? I don't extract it yet with ipsw so you'd have pull it out manually. I'll also take a look soon

**Comment by blacktop** [comment]
nvm, it's not the DriverKit dsc stuff:

Header
======
Magic             = "dyld_v1  arm64e"
UUID              = E1C123EE-360D-3345-AAC1-437D66355AF1
Platform          = driverKit
Max Slide         = 0x7FC98000 (ASLR entropy: 17-bits)
Num SubCaches     = 0
SubCache Group ID = 0xb28
Sym SubCache UUID = 85B8C120-FB40-3750-9FAC-0C96C06D1303

Local Symbols (nlist array):      0MB, offset:  0x0004F82A0 -> 0x000514910
Local Symbols (string pool):      0MB, offset:  0x000514910 -> 0x00054DC07
Code Signature:                   0MB, offset:  0x0004F4000 -> 0x0004F8000
ImagesText Info ( 27 entries):   0KB, offset:  0x000000468 -> 0x0000007C8
Patch Info:                       0MB, address: 0x1864DC370 -> 0x1864EDA9C
Closures:                         0MB, address: 0x1864EF548 -> 0x1864F1960
Closures Trie:                    0KB, address: 0x1864F1960 -> 0x1864F1BA0
Shared Region:                    0GB, address: 0x180000000 -> 0x1864F4000

Mappings
========
|     SEG      | INITPROT | MAXPROT |        SIZE         |   ADDRESS   | FILE OFFSET |  SLIDE INFO (V3) OFFSET  | FLAGS |
|--------------|----------|---------|---------------------|-------------|-------------|--------------------------|-------|
| __TEXT       | r-x      | r-x     | 0x00368000 (3.6 MB) | 0x180000000 | 0x00000000  |                          | 0     |
| __DATA_CONST | r--      | rw-     | 0x00008000 (33 kB)  | 0x182368000 | 0x00368000  | 0x003d4000 -> 0x003d8000 | 4     |
| __DATA       | rw-      | rw-     | 0x00028000 (164 kB) | 0x184370000 | 0x00370000  | 0x003dc000 -> 0x003e0000 | 0     |
| __AUTH       | rw-      | rw-     | 0x00010000 (66 kB)  | 0x184398000 | 0x00398000  | 0x003e4000 -> 0x003e8000 | 1     |
| __AUTH_CONST | r--      | rw-     | 0x0002c000 (180 kB) | 0x1843a8000 | 0x003a8000  | 0x003ec000 -> 0x003f0000 | 5     |
| __LINKEDIT   | r--      | r--     | 0x00120000 (1.2 MB) | 0x1863d4000 | 0x003d4000  |                          | 0     |
| __TEXT       | r-x      | r-x     | 0x00004000 (16 kB)  | 0x00000000  | 0x004f4000  |                          | 0     |

Images
======
   1:  /System/DriverKit/System/Library/Frameworks/AudioDriverKit.framework/AudioDriverKit  (1.0.0)
   2:  /System/DriverKit/System/Library/Frameworks/DriverKit.framework/DriverKit  (1.0.0)
   3:  /System/DriverKit/System/Library/Frameworks/HIDDriverKit.framework/HIDDriverKit  (1.0.0)
   4:  /System/DriverKit/System/Library/Frameworks/HIDDriverKit.framework/HIDDriverKit_development  (1.0.0)
   5:  /System/DriverKit/System/Library/Frameworks/NetworkingDriverKit.framework/NetworkingDriverKit  (1.0.0)
   6:  /System/DriverKit/System/Library/Frameworks/NetworkingDriverKit.framework/NetworkingDriverKit_development  (1.0.0)
   7:  /System/DriverKit/System/Library/Frameworks/PCIDriverKit.framework/PCIDriverKit  (1.0.0)
   8:  /System/DriverKit/System/Library/Frameworks/SerialDriverKit.framework/SerialDriverKit  (1.0.0)
   9:  /System/DriverKit/System/Library/Frameworks/USBDriverKit.framework/USBDriverKit  (1.0.0)
  10:  /System/DriverKit/System/Library/Frameworks/USBSerialDriverKit.framework/USBSerialDriverKit  (1.0.0)
  11:  /System/DriverKit/System/Library/PrivateFrameworks/MallocStackLogging.framework/MallocStackLogging  (1.0.0)
  12:  /System/DriverKit/usr/lib/libSystem.dylib  (1308.0.0)
  13:  /System/DriverKit/usr/lib/libc++.dylib  (907.1.0)
  14:  /System/DriverKit/usr/lib/libc++abi.dylib  (907.1.0)
  15:  /System/DriverKit/usr/lib/system/libcompiler_rt.dylib  (102.3.0)
  16:  /System/DriverKit/usr/lib/system/libcorecrypto.dylib  (1167.0.0)
  17:  /System/DriverKit/usr/lib/system/libdispatch.dylib  (1319.0.0)
  18:  /System/DriverKit/usr/lib/system/libdyld.dylib  (1.0.0)
  19:  /System/DriverKit/usr/lib/system/libmacho.dylib  (985.0.0)
  20:  /System/DriverKit/usr/lib/system/libsystem_blocks.dylib  (79.0.0)
  21:  /System/DriverKit/usr/lib/system/libsystem_c.dylib  (1496.0.0)
  22:  /System/DriverKit/usr/lib/system/libsystem_kernel.dylib  (7938.0.0)
  23:  /System/DriverKit/usr/lib/system/libsystem_m.dylib  (3202.0.0)
  24:  /System/DriverKit/usr/lib/system/libsystem_malloc.dylib  (360.0.0)
  25:  /System/DriverKit/usr/lib/system/libsystem_platform.dylib  (269.0.0)
  26:  /System/DriverKit/usr/lib/system/libsystem_pthread.dylib  (484.0.0)
  27:  /System/DriverKit/usr/lib/system/libsystem_trace.dylib  (1363.0.0)

**Comment by blacktop** [comment]
010 wasn't able to find the string `/sbin/launchd` in the dsc.  I believe if it was in there it would be mentioned somewhere?

**Comment by doronz88** [comment]
You are right and that was mistake. It's true that many of the binaries from the OS appear there but it seems not all of them. `/usr/libexec/lockdownd` does appear there with its UUID. Today I'll keep trying to figure out this section structure.
Since this matter now is completely unrelated to the opened issue I rather we discuss it's developement somewhere else. You can PM me if you'd like, or if you rather we still talk in here.

Anyhow, feel free to close the issue :)

**Comment by doronz88** [comment]
It's a really hack-ish way but it works:
https://github.com/doronz88/pymobiledevice3/pull/90/files

The `pymobiledevice3/dsc_uuid_map.json` will now contain maps for UUID-imagePath for every unique DSC file so we can now symbolicate return addresses ourselves.

**Comment by blacktop** [comment]
VERY nice!  👍

**Comment by blacktop** [comment]
Working on the :new: emulator I had a friend tell me I should look at closures as they include initializers *(valuable for emulation setup 😉 )* and in so I discovered that data you mentioned a LONG time ago.  So these binaries aren't embedded in the shared_cache, but their "closures" are.  So for completeness here is that data *(which will soon be exposed in a NEW `ipsw dyld image` command)*:

> **NOTE:** I cannot *yet* parse these in the iOS15 caches.

```bash
❯ ipsw dyld image 18H17__iPhone9,1_3_iPhone10,1_4/dyld_shared_cache_arm64 /usr/libexec/lockdownd
```

```
Name:              /usr/libexec/lockdownd
Flags:             objc|exe|readonly_data|precomp_objc
UUID:              30202A62-07CD-3128-9CCD-CCE69AE5CBBF
CDHash:            300cc709eeeef2cdb62402f21e8d0c0969ff73c1
Code Signature:    offset: 0x000e3f90-0x000e7860, size: 14544
Total VM Size:     0xec000
```
Mappings:
| FILE OFFSET | FILE SIZE  |  VM SIZE   | PROT |
|-------------|------------|------------|------|
| 0x00000000  | 0x00000000 | 0x00000000 | ---  |
| 0x00000000  | 0x000bc000 | 0x000bc000 | r-x  |
| 0x000bc000  | 0x00014000 | 0x00014000 | -w-  |
| 0x000d0000  | 0x00008000 | 0x00008000 | rw-  |
| 0x000d8000  | 0x00010000 | 0x00014000 | r--  |

Dependents:
```
	regular ) /System/Library/PrivateFrameworks/UserManagement.framework/UserManagement
	regular ) /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
	regular ) /usr/lib/libamsupport.dylib
	regular ) /System/Library/PrivateFrameworks/CrashReporterSupport.framework/CrashReporterSupport
	regular ) /System/Library/Frameworks/LocalAuthentication.framework/LocalAuthentication
	regular ) /System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
	regular ) /System/Library/PrivateFrameworks/CoreUtils.framework/CoreUtils
	regular ) /System/Library/PrivateFrameworks/FindMyDevice.framework/FindMyDevice
	regular ) /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
	regular ) /System/Library/PrivateFrameworks/MobileActivation.framework/MobileActivation
	regular ) /System/Library/PrivateFrameworks/SpringBoardServices.framework/SpringBoardServices
	regular ) /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
	regular ) /usr/lib/libextension.dylib
	regular ) /System/Library/PrivateFrameworks/ServiceManagement.framework/ServiceManagement
	regular ) /System/Library/PrivateFrameworks/AppSupport.framework/AppSupport
	regular ) /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
	regular ) /System/Library/Frameworks/IOKit.framework/IOKit
	regular ) /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
	regular ) /System/Library/PrivateFrameworks/MobileStorage.framework/MobileStorage
	regular ) /System/Library/PrivateFrameworks/Bom.framework/Bom
	regular ) /System/Library/Frameworks/Security.framework/Security
	regular ) /System/Library/PrivateFrameworks/MobileWiFi.framework/MobileWiFi
	regular ) /System/Library/PrivateFrameworks/MobileInstallation.framework/MobileInstallation
	regular ) /System/Library/PrivateFrameworks/MobileKeyBag.framework/MobileKeyBag
	regular ) /System/Library/PrivateFrameworks/CoreTime.framework/CoreTime
	regular ) /usr/lib/liblockdown.dylib
	regular ) /usr/lib/libz.dylib
	regular ) /usr/lib/libMobileCheckpoint.dylib
	regular ) /usr/lib/libMobileGestalt.dylib
	regular ) /usr/lib/libAccessibility.dylib
	regular ) /usr/lib/libobjc.dylib
	regular ) /usr/lib/libMobileGestaltExtensions.dylib
	regular ) /usr/lib/librpcsvc.dylib
	regular ) /System/Library/Frameworks/CoreServices.framework/CoreServices
```

Init Order:
```
	/usr/lib/system/libsystem_blocks.dylib
	/usr/lib/system/libdispatch.dylib
	/usr/lib/system/libxpc.dylib
	/usr/lib/system/libsystem_trace.dylib
	/usr/lib/librpcsvc.dylib
	/usr/lib/libc++.dylib
	/usr/lib/libobjc.dylib
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
	/usr/lib/libnetwork.dylib
	/usr/lib/libextension.dylib
	/System/Library/PrivateFrameworks/CoreDuet.framework/CoreDuet
	/usr/lib/libcryptex_core.dylib
	/usr/lib/libcryptex_interface.dylib
	/usr/lib/libcryptex.dylib
	/System/Library/Frameworks/CoreText.framework/CoreText
```
