### ISSUE TITLE
sign not the same with apple when input is the same ,why?

### ISSUE THREAD

**Issue by lilili87222** [blacktop/ipsw#284]
sign data not the same with apple codesign with the same input .
sign with ipsw ,and view --sig  ,your result is parameter: **_ABSENT_**
but see the macho signed with codesign ,the result is parameter: **_NULL_**

CMS_ContentInfo: 
  contentType: pkcs7-signedData (1.2.840.113549.1.7.2)
  d.signedData: 
    version: 1
    digestAlgorithms:
        algorithm: sha256 (2.16.840.1.101.3.4.2.1)
        parameter: **_ABSENT_**
    encapContentInfo: 
      eContentType: pkcs7-data (1.2.840.113549.1.7.1)
      eContent: <ABSENT>
    certificates:
      d.certificate: 
        cert_info: 
          version: 2
          serialNumber: 165735053884535624300751353685070104046
          signature: 
            algorithm: sha256WithRSAEncryption (1.2.840.113549.1.1.11)
            parameter: NULL
          issuer: C=US, O=Apple Inc., OU=Apple Certification Authority, CN=Apple Root CA
          validity: 
            notBefore: Feb 19 18:13:47 2020 GMT
            notAfter: Feb 20 00:00:00 2030 GMT
          subject: CN=Apple Worldwide Developer Relations Certification Authority, OU=G3, O=Apple Inc., C=US
          key:           X509_PUBKEY:

**Comment by blacktop** [comment]
I'm having difficulty following your issue.

Can you post the exact cmds you are using for `ipsw` and for `codesign` and if you can share the binary too that would help.

Thanks!

**Comment by lilili87222** [comment]
I have tested, it does not affect the work although it is different.

**Comment by lilili87222** [comment]
I have tested, it does not affect the work although it is different.
