### ISSUE TITLE
Programatically identify extracted kernelcache

### ISSUE THREAD

**Issue by kit-981** [blacktop/ipsw#299]
```
$ ipsw download appledb --kernel --build 21A5326a --os iOS --device iPhone13,3
```

I end up with a file at `21A5326a__iPhone13,2_3/kernelcache.release.iPhone13,2_3` and `21A5326a__iPhone13,2_3/kernelcache.research.iPhone13,2`.

```
ipsw info -l -r https://updates.cdn-apple.com/2023SummerSeed/fullrestores/042-38224/24217441-DF42-4A44-8D28-B6F597733A8A/iPhone13,2,iPhone13,3_17.0_21A5326a_Restore.ipsw | rg kernelcache
kernelcache.release.iphone13                                           17 MB
kernelcache.research.iphone13                                          17 MB
```

It looks like these are renamed. Is it possible to avoid renaming the file? Parsing the renamed filename isn't straight forward because commas are used to delimiter phone minor versions (eg. `iPhone13,2_3`) but also devices like `iPhone` and `iPod`  when the same kernelcache is used for both (https://github.com/blacktop/ipsw/blob/master/pkg/info/info.go#L520). This seems hard to cope with programmatically. Do you have other suggestions? Ultimately, I just want to extract the release kernelcache and get the path.

Are the extracted files guaranteed to all include what is specified with `--device`? I don't have an example but I remember there being a few times where multiple release kernelcaches were extracted from a single IPSW but for different devices and so I had to resort to parsing the filename to identify which was for my device.

**Comment by blacktop** [comment]
I recently added the `--json` flag to output the extracted file paths as JSON and for the reasons you have presented kernels are special so for those the JSON contains a mapping of the files  to their devices

**Comment by blacktop** [comment]
```bash
❯ ipsw extract -k UniversalMac_14.0_23A5337a_Restore.ipsw --json | jq .
   • Extracting kernelcache
```
```json   
{
  "23A5337a__Mac13,1_2_Mac14,2_3_5_6_7_8_9_10_12_13_14_15_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/kernelcache.release.Mac13,1_2_MacBookPro18,1_2_3_4": [
    "Mac13,1",
    "Mac13,2",
    "MacBookPro18,1",
    "MacBookPro18,2",
    "MacBookPro18,3",
    "MacBookPro18,4"
  ],
  "23A5337a__Mac13,1_2_Mac14,2_3_5_6_7_8_9_10_12_13_14_15_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/kernelcache.release.Mac14,2_3_7_15": [
    "Mac14,2",
    "Mac14,3",
    "Mac14,7",
    "Mac14,15"
  ],
  "23A5337a__Mac13,1_2_Mac14,2_3_5_6_7_8_9_10_12_13_14_15_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/kernelcache.release.Mac14,5_6_8_9_10_12_13_14": [
    "Mac14,5",
    "Mac14,6",
    "Mac14,8",
    "Mac14,9",
    "Mac14,10",
    "Mac14,12",
    "Mac14,13",
    "Mac14,14"
  ],
  "23A5337a__Mac13,1_2_Mac14,2_3_5_6_7_8_9_10_12_13_14_15_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/kernelcache.release.MacBookAir10,1_MacBookPro17,1_Macmini9,1_iMac21,1_2": [
    "MacBookAir10,1",
    "MacBookPro17,1",
    "Macmini9,1",
    "iMac21,1",
    "iMac21,2"
  ],
  "23A5337a__Mac13,1_2_Mac14,2_3_5_6_7_8_9_10_12_13_14_15_MacBookAir10,1_MacBookPro17,1_MacBookPro18,1_2_3_4_Macmini9,1_VirtualMac2,1_iMac21,1_2/kernelcache.release.VirtualMac2,1": [
    "VirtualMac2,1"
  ]
}
```

**Comment by blacktop** [comment]
I can try and do something similar with the `ipsw` downloader `--kernel` commands.

I'm also planning on adding a templating engine to allow users to customize the extracted file directory/filename as well (but don't have a firm timeline for that feature yet)

**Comment by kit-981** [comment]
I missed `--json` on `ipsw extract`. That's enough for me. Thanks!
