### ISSUE TITLE
viper.GetString is slow and should not be called on a hot path

### ISSUE THREAD

**Issue by saagarjha** [blacktop/ipsw#308]
https://github.com/blacktop/ipsw/blob/256e4479047164244dc7616518ecad40354af2a2/cmd/ipsw/cmd/dyld/dyld_search.go#L395 is 40% of total CPU time (and over 80% if you remove GC) when calling `ipsw dyld search -s` on a shared cache.

<img width="680" alt="image" src="https://github.com/blacktop/ipsw/assets/13786931/98b16aa5-197a-448d-95f6-01494448573b">

**Comment by blacktop** [comment]
# 😍

**Comment by blacktop** [comment]
cutting release now, keep em' coming 😁 👍

**Comment by blacktop** [comment]
that's a horrible pattern that I got used to doing, and prob can remove it from a LOT of the commands 😞

**Comment by saagarjha** [comment]
Thanks, this makes ipsw dyld search about 3x faster on my machine
