### ISSUE TITLE
Add option for choosing what to do with existing file 

### ISSUE THREAD

**Issue by SoneeJohn** [blacktop/ipsw#31]
Currently, the only option is to skip-all I would like an option for the others. See command:

```
ipsw download --verbose latest --yes --device iPhone11,2
   • Latest release found is: 14.7.1
   • URLs to Download:        
   • https://updates.cdn-apple.com/2021SummerFCS/fullrestores/071-73966/B2F4517C-A57C-48D3-88B6-9A718A774EA6/iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_14.7.1_18G82_Restore.ipsw
   • Getting IPSW              build=18G82 device=iPhone11,2 version=14.7.1
? Previous download of iPhone11,2,iPhone11,4,iPhone11,6,iPhone12,3,iPhone12,5_14.7.1_18G82_Restore.ipsw can be resumed:  [Use arrows to move, type to filter]
  resume
  skip
> skip all
  restart

```

**Comment by SoneeJohn** [comment]
On another note, how do use the configuration file? I noticed:

```
Global Flags:
      --config string   config file (default is $HOME/.ipsw.yaml)
  -V, --verbose         verbose output
```

**Comment by blacktop** [comment]
Yeah I started working on the concept on a config.  It's not fleshed out at all, but it will hopefully have settings for ALL the flags etc to help people running it more as a service than CLI, there is also plans to turn it into a web service w/ RESTful API AND a GUI w/ disassembler etc (that's gunna take a LOT of weekends to do though 😩) 😏

**Comment by blacktop** [comment]
Adding your requested :new: flags in PR #45 as well as a working (although not fully fleshed out config system)

`~/.ipsw.yaml `

```yaml
download:
  confirm: true
  version: 14.8.1
  white-list:
    - iPod9,1
    - iPhone14,2
  ota:
    platform: macOS

```

**Comment by blacktop** [comment]
https://github.com/blacktop/ipsw.git/releases/tag/v3.0.95 let me know how it goes and re-open if you find any issues with it. 👍
