### ISSUE TITLE
ipsw dyld symaddr --image failure on macOS intel DSCs

### ISSUE THREAD

**Issue by blacktop** [blacktop/ipsw#314]
dhinak@Dhinaks-MacBook-Air 22F66 % ipsw dyld symaddr dyld_shared_cache_x86_64 --out syms.json > /dev/null
   • parsing public symbols...
   • parsing private symbols...
   ⨯ failed to parse private symbols: failed to parse local syms for image libobjc.A.dylib: dyld shared cache does NOT contain local symbols info

dhinak@Dhinaks-MacBook-Air 22F66 % ipsw dyld symaddr dyld_shared_cache_x86_64 --out syms.json -i libobjc.A.dylib
   • parsing private symbols for image...
      • failed to parse local syms for image libobjc.A.dylib: dyld shared cache does NOT contain local symbols info
   • parsing public symbols for image...
0x7ff800076297: (regular)  _NXCompareHashTables
blah more symbols blah

@dortania

**Comment by blacktop** [comment]
This is not an error, it's just letting you know there's no local symbols

**Comment by NSExceptional** [comment]
@blacktop Is it not possible to parse the symbol table manually the way you can with a mach-O binary to see non-exported symbols? I need to iterate over all functions in an image for something I'm working on

Couldn't this project just mimic how `dlsym` works at least for exported symbols?

**Comment by blacktop** [comment]
> [@blacktop](https://github.com/blacktop) Is it not possible to parse the symbol table manually the way you can with a mach-O binary to see non-exported symbols? I need to iterate over all functions in an image for something I'm working on
> 
> Couldn't this project just mimic how `dlsym` works at least for exported symbols?

is this something different than `ipsw dsc macho DSC DYLIB --symbols -V` ?

**Comment by NSExceptional** [comment]
> is this something different than `ipsw dsc macho DSC DYLIB --symbols -V` ?

Maybe I'm not doing it right, but I'm not getting any actual symbols printed when I run this for example:

```
cachepath=/Library/Developer/CoreSimulator/Caches/dyld/24G84/com.apple.CoreSimulator.SimRuntime.iOS-18-6.22G86/dyld_sim_shared_cache_arm64
ipsw dsc macho $cachepath Foundation --symbols -V
```

It prints all the commands and sections/segments, but not symbols. I ended up being able to whip something up with Copilot that parses the export tries, but I'd still love to be able to do it with this tool!

**Comment by blacktop** [comment]
@NSExceptional this should be fixed in next release, thank you for letting me know! ❤️

**Comment by blacktop** [comment]
@NSExceptional release out, please test and let me know if the issue is fixed

**Comment by NSExceptional** [comment]
Fixed! Thank you so much! :D

**Comment by NSExceptional** [comment]
Hmm one other thing—I can make a separate issue for this if you'd like, but—when I pipe the output to a file, there's a bunch of ANSI escape codes / control codes in the output. Can you try to detect when the output is being piped to a file and omit them?
<img width="906" height="308" alt="Image" src="https://github.com/user-attachments/assets/25f5d973-ff28-4d23-a220-89482930c1e2" />

**Comment by blacktop** [comment]
> Hmm one other thing—I can make a separate issue for this if you'd like, but—when I pipe the output to a file, there's a bunch of ANSI escape codes / control codes in the output. Can you try to detect when the output is being piped to a file and omit them? <img alt="Image" width="906" height="308" src="https://private-user-images.githubusercontent.com/8371943/508486540-25f5d973-ff28-4d23-a220-89482930c1e2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE5NTgyNzYsIm5iZiI6MTc2MTk1Nzk3NiwicGF0aCI6Ii84MzcxOTQzLzUwODQ4NjU0MC0yNWY1ZDk3My1mZjI4LTRkMjMtYTIyMC04OTQ4MjkzMGMxZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMDFUMDA0NjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBhNmY1Yjc5YmRlZDVmY2JlZjYyNWNkYThiZTY4ZDZlMjAxNTJiYzkxZjc3ZTVjNDc3ZDExZWYyMGY3OGQ4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NVVfhCnDQ1yZE_etKyRbm72orbxe7C4XpWGCM_-a-lU">

`--no-color` or `NO_COLOR=1`
