### ISSUE TITLE
Unable to download IPA from App Store using 2FA enabled account

### ISSUE THREAD

**Issue by zhangyoufu** [blacktop/ipsw#329]
```
   • POST Download: (200):
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<plist version="1.0">
<dict>
<key>pings</key>
<array></array>
<key>failureType</key><string>5002</string>
<key>customerMessage</key><string>An unknown error has occurred</string>
<key>m-allowed</key><false/>
</dict>
</plist>
```
```
   ⨯ failed to download app XXXXXX: no items found in download response
```

**Comment by zhangyoufu** [comment]
I tried to remove `ipsw-vault` from KeyChain and re-login. It looks strange that `ipsw` did not ask for 2FA and report error during download.

I tried `ipatool download`, which asks for 2FA and could download app using the same account.

**Comment by blacktop** [comment]
thanks for letting me know

**Comment by blacktop** [comment]
should be fixed in next release, thx again

**Comment by dmtch** [comment]
Was it really solved?
I faced the same bug right now (using build ipsw_3.1.450_windows_x86_64).

**Comment by blacktop** [comment]
I don't have a windows machine to test, but it did work on macOS.  the cmd stores your cress security in the OS's secure cred storage tech, not sure what that is on windows, but if you go and find the `ipso` entry there and delete it and retry it should work?

**Comment by dmtch** [comment]
I don't understand how exactly, but the problem was fixed after some manual interactions with AppStore app on my iPad and fiddling with ipatool (which downloads the app firstly). Probably, it was something related to the state of my appleid account.
