### ISSUE TITLE
brew install fail

### ISSUE THREAD

**Issue by uaex** [blacktop/ipsw#35]
Issue:
```
==> Downloading https://github.com/blacktop/ipsw/releases/download/v3.0.71/ipsw_
Already downloaded: /Users/gumingjun/Library/Caches/Homebrew/downloads/cf3b3a77e11173cdf291efe4579989d22801842cde309d29766f2e33f682a1b2--ipsw_3.0.71_macOS_x86_64.tar.gz
==> Installing ipsw from blacktop/tap
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

I install other packages well

**Comment by blacktop** [comment]
Hmm very strange, I also use brew to install and I have installed 3.0.71 successfully. Can you try uninstalling and reinstalling?

**Comment by uaex** [comment]
> Hmm very strange, I also use brew to install and I have installed 3.0.71 successfully. Can you try uninstalling and reinstalling?

I have this issue when I uninstall 3.0.69 and reinstall latest
my env:
macOS 12.0 Beta (21A5506j)
Homebrew 3.2.12-54-gaecadd2
Gem 3.2.27

I use binary from repo now.

**Comment by uaex** [comment]
I upgrade Xcode 13 RC1 and reinstall command line developer tools to resolve it. It seems like an incompatible problem from brew using macOS 12
