### ISSUE TITLE
Can't extract KEXTs

### ISSUE THREAD

**Issue by Luxvao** [blacktop/ipsw#364]
I'm trying to extract kexts from ios 12.5.7 kernel for iPhone7,2 but I get the `kernel type is not MH_FILESET (KEXT-xtraction not supported yet)` error. Can I just not extract kexts from ios 12.5.7?

**Comment by blacktop** [comment]
Currently `ipsw` doesn't support KEXT-xtraction from OLD IPSWs (as this is very different than the NEW style that uses `MH_FILESET`)

I might support it in the future, however, but no timeline at the moment.
