### ISSUE TITLE
Failed to parse iOS 15.0.1 kernelcache

### ISSUE THREAD

**Issue by KpwnZ** [blacktop/ipsw#37]
Failed to parse kernelcache for iOS 15.0.1 on macOS Monterey beta 9.
```
$ ipsw kernel dec kernelcache.release.ipad6f
   • Decompressing kernelcache
Error: failed parse compressed kernelcache Img4: failed to ASN.1 parse kernelcache: asn1: structure error: length too large
```
```
$ ipsw kernel kexts kernelcache.release.ipad6b            
Error: section __PRELINK_INFO.__kmod_start not found
```

**Comment by blacktop** [comment]
So that looks like you pulled the im4p file out of the ipsw.  You could have extracted with:
```bash
$ ipsw extract -k IPSW.ipsw
```
However, what you could do with the file you have is:
```bash
$ ipsw img4 extract kernelcache.release.ipad6f

**Comment by blacktop** [comment]
Just to confirm can you run:
```bash
$ file kernelcache.release.ipad6f
```

**Comment by blacktop** [comment]
Can you please tell me what device that is for? I can't remember what `ipad6f` is off the top of my head.

**Comment by blacktop** [comment]
Ok got it.  I was able to recreate the issue.  

Very strange it works for iPhone12,1 but not the iPad6,11 ??  

I usually test the iPhone and the iPod, but not the iPad.  Thank you for letting me know about this!

**Comment by KpwnZ** [comment]
> Ok got it. I was able to recreate the issue.
> 
> Very strange it works for iPhone12,1 but not the iPad6,11 ??
> 
> I usually test the iPhone and the iPod, but not the iPad. Thank you for letting me know about this!

Thanks for your great work!

**Comment by KpwnZ** [comment]
Can confirm `kexts` command is working now! 
```
$ ipsw kernel kexts 19A348/kernelcache.release.ipad6f
FOUND: 222
0xfffffff00535c000: com.apple.kpi.bsd (21.0.0)
0xfffffff00535c080: com.apple.kpi.libkern (21.0.0)
0xfffffff00535c100: com.apple.kpi.mach (21.0.0)
.........
```

**Comment by blacktop** [comment]
> So I am releasing a fix now for the `ipsw kernel kexts` cmd that I believe should cover the cases iPhone/iPod and iPad kernels.
> 
> For `sbopts` it looks like for the phones that info is in the kernel's `__DATA_CONST.__const` BUT in the iPad it's in the `com.apple.security.sandbox` kext's `__DATA_CONST.__const` ?? I need to think a lil' harder on a way to detect which/where I should look and will let you know when I get it merged in.

I fixed this a while back I guess, because I just tested it and it works now :share
