### ISSUE TITLE
`ipsw diff` - add machos file diffs

### ISSUE THREAD

**Issue by clearbluejar** [blacktop/ipsw#371]
Currently, `ipsw diff` reports changes across the kernel cache, entitlements,  dylibs in the DSC, etc. (which is amazing). I'd also be interested in seeing changes across macho binaries.

I know that sometimes (always?) the version for macho files will increase for a new build, even though there may not be meaningful (code) changes to a file. 

Example of version++ and framework version updates, but no code change:
```diff
diff --git a/23A b/23B
index 2b58ac1..cb5e0d7 100755
--- a/23A
+++ b/23B
@@ -67,52 +67,52 @@ Flags         = NoUndefs, DyldLink, TwoLevel, BindsToWeak, PIE
         External Reloc Entries: None
            Local Reloc Entries: None
 009: LC_LOAD_DYLINKER            /usr/lib/dyld
-010: LC_UUID                     AD21607E-425B-38CF-A59D-524B2BF01AAD
-011: LC_BUILD_VERSION            Platform: macOS, MinOS: 14.0, SDK: 14.0, Tool: ld (902.8)
-012: LC_SOURCE_VERSION           2563.0.0.0.0
+010: LC_UUID                     F1A6497B-318A-3D2A-9FC1-36E640FF6692
+011: LC_BUILD_VERSION            Platform: macOS, MinOS: 14.1, SDK: 14.1, Tool: ld (902.8)
+012: LC_SOURCE_VERSION           2565.0.0.0.0
 013: LC_MAIN                     Entry Point: 0x0000000000012b9b, Stack Size: 0x0
-014: LC_LOAD_DYLIB               /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (2048.1)
-015: LC_LOAD_DYLIB               /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (2471.0)
+014: LC_LOAD_DYLIB               /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (2106.0)
+015: LC_LOAD_DYLIB               /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (2487.20.104)
```

Reporting all those changes would provide loud and useless data. So perhaps as an additional check, the diff check for macho files within the firmware would check for:
1. version++
2.  change in file size
3.  other indicators of meaningful change

Also, for the dylibs, it would be interesting to see the file size deltas as well. Perhaps this is a multi-feature request. 😀
Maybe for dylibs if a version is updated likely there is code changed? TBD, but might want to consider some extra info for the currently reported dylibs. Looks like currently the [versions are checked](https://github.com/blacktop/ipsw/blob/master/internal/diff/diff.go#L433-L450).

**Comment by blacktop** [comment]
cutting a release now that adds MachO 'diffing'.  Let me know what you think, I'm sure I'm happy w/ the output yet, but the Dylibs should work the same so I can add that next pretty quickly.

**Comment by blacktop** [comment]
https://gist.github.com/blacktop/dc18bcc2bfe9808386cd4575e1eda029

**Comment by clearbluejar** [comment]
> Let me know what you think, I'm NOT sure I'm happy w/ the output yet, but the Dylibs should work the same so I can add that next pretty quickly.

Love that it shows the sections and how their size has changed, even showing the function counts changes.  
![image](https://github.com/blacktop/ipsw/assets/3752074/1043b71c-ad30-424e-a53d-2d1052c5409e)
![image](https://github.com/blacktop/ipsw/assets/3752074/47ca1adc-da32-4eeb-bce6-c420099898c2)

There is a slight inconsistencies in the main TOC with dylib getting direct links to updated and machos not have it.
![image](https://github.com/blacktop/ipsw/assets/3752074/79b6d322-d28a-41dd-97ad-268b765aaf2d)


One thing that is difficult to see immediately was how many files changed. I think something as simple as a total count could be helpful for a quick glance from the TOC.

![image](https://github.com/blacktop/ipsw/assets/3752074/f516b696-997f-497a-bb1f-54c5c54abbd3)
I manually edited a version here:   https://gist.github.com/clearbluejar/1983ecdd3f2e2a537b2e912e6a8cd8f2

Actually counts for each might one that makes sense could be helpful.

---

All that being said, having the ability to detect the changes is the primary ask, and it seems to be working well!

**Comment by clearbluejar** [comment]
I tried the latest ipsw release with the command I was using  previously successfully with `Macmin9,1` and received a new invalid memory exception:

```
% ipsw version
Version: 3.1.435, BuildTime: 2023-12-18T06:47:45Z
```

```
% ipsw diff /ipsw/Macmin9,1/UniversalMac_14.0_23A344_Restore.ipsw /ipsw/Macmin9,1/UniversalMac_14.1_23B74_Restore.ipsw  -V
Using config file: /Users/yoda/.config/ipsw/config.yml
   • Diffing KERNELCACHES
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac13g from UniversalMac_14.0_23A344_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac13j from UniversalMac_14.0_23A344_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac14g from UniversalMac_14.0_23A344_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac14j from UniversalMac_14.0_23A344_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.vma2 from UniversalMac_14.0_23A344_Restore.ipsw
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac13g from UniversalMac_14.1_23B74_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac13j from UniversalMac_14.1_23B74_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac14g from UniversalMac_14.1_23B74_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac14j from UniversalMac_14.1_23B74_Restore.ipsw
      • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.vma2 from UniversalMac_14.1_23B74_Restore.ipsw
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
      • Parsing Kernelcache IMG4
      • Decompressing Kernelcache
         • Kernelcache is LZFSE compressed
   • failed to get kext start addresses: section __PRELINK_INFO.__kmod_start not found
   • failed to get kext start addresses: section __PRELINK_INFO.__kmod_start not found
   • Diffing DYLD_SHARED_CACHES
   • Mounting 'Old' SystemOS DMG
      • Extracted 078-35929-533.dmg from UniversalMac_14.0_23A344_Restore.ipsw
      • Mounting 078-35929-533.dmg
   • Mounting 'New' SystemOS DMG
      • Extracted 097-26443-097.dmg from UniversalMac_14.1_23B74_Restore.ipsw
      • Mounting 097-26443-097.dmg
   • Parsing Cache             cache=/tmp/078-35929-533.dmg.mount/System/Library/dyld/dyld_shared_cache_arm64e
   • Parsing Cache             cache=/tmp/097-26443-097.dmg.mount/System/Library/dyld/dyld_shared_cache_arm64e
   • Diffing MachOs
   • Scanning filesystem
      • Extracted 078-29483-526.dmg from UniversalMac_14.0_23A344_Restore.ipsw
      • Mounting filesystem 078-29483-526.dmg
      • Unmounting 078-29483-526.dmg
      • Unmounting 'Old' SystemOS DMG
      • Unmounting 'New' SystemOS DMG
      • Deleting 'Old' SystemOS DMG
      • Deleting 'New' SystemOS DMG
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104e31378]

goroutine 1 [running]:
github.com/blacktop/ipsw/internal/search.scanDmg.func3({0x140650ffb90, 0x67}, {0x0?, 0x0?}, {0x14064e38b40?, 0x5f?})
	github.com/blacktop/ipsw/internal/search/search.go:55 +0x28
path/filepath.walk({0x14064e38b40, 0x5f}, {0x1068c60b0, 0x14001bb9ee0}, 0x140029a5048)
	path/filepath/path.go:497 +0x170
path/filepath.walk({0x14064e389c0, 0x57}, {0x1068c60b0, 0x14001bb9e10}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x14064e388a0, 0x51}, {0x1068c60b0, 0x14001bb9d40}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x1400235b590, 0x49}, {0x1068c60b0, 0x14001bad040}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x1400235ac30, 0x46}, {0x1068c60b0, 0x14001bac5b0}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x1400423c190, 0x42}, {0x1068c60b0, 0x14001b8ed00}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x14002162ec0, 0x3a}, {0x1068c60b0, 0x140008b3ba0}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x14002162e00, 0x35}, {0x1068c60b0, 0x140008b3ad0}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x14066062300, 0x2b}, {0x1068c60b0, 0x14066154b60}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x14004df8270, 0x23}, {0x1068c60b0, 0x14004ddc4e0}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.walk({0x1406478b960, 0x1c}, {0x1068c60b0, 0x14004ddc000}, 0x140029a5048)
	path/filepath/path.go:501 +0x1d4
path/filepath.Walk({0x1406478b960, 0x1c}, 0x14019177048)
	path/filepath/path.go:572 +0x6c
github.com/blacktop/ipsw/internal/search.scanDmg({0x16b9a3912, 0x40}, {0x14019b30780, 0x11}, {0x105fad999, 0xa}, 0x1074dafa0?)
	github.com/blacktop/ipsw/internal/search/search.go:54 +0x4d0
github.com/blacktop/ipsw/internal/search.ForEachMachoInIPSW({0x16b9a3912, 0x40}, 0x140029a9288?)
	github.com/blacktop/ipsw/internal/search/search.go:108 +0xcc
github.com/blacktop/ipsw/internal/commands/macho.DiffIPSW({0x16b9a3912, 0x40}, {0x16b9a3953, 0x3f}, 0x140029a5af0)
	github.com/blacktop/ipsw/internal/commands/macho/diff.go:128 +0x10c
github.com/blacktop/ipsw/internal/diff.(*Diff).parseMachos(...)
	github.com/blacktop/ipsw/internal/diff/diff.go:517
github.com/blacktop/ipsw/internal/diff.(*Diff).Diff(0x1400053aa00)
	github.com/blacktop/ipsw/internal/diff/diff.go:197 +0x870
github.com/blacktop/ipsw/cmd/ipsw/cmd.glob..func9(0x140004a9e00?, {0x140007fd450, 0x2, 0x105f9acc8?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/diff.go:75 +0x348
github.com/spf13/cobra.(*Command).execute(0x1071d3760, {0x140007fd400, 0x5, 0x5})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1071d5fa0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:70 +0x24
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x1c
```

**Comment by blacktop** [comment]
Here's the updated next version's output 
- https://gist.github.com/blacktop/dc18bcc2bfe9808386cd4575e1eda029

**Comment by clearbluejar** [comment]
Totals look good in the TOC! 👍

**Comment by blacktop** [comment]
> I tried the latest ipsw release with the command I was using previously successfully with `Macmin9,1` and received a new invalid memory exception:
> 
> ```
> % ipsw version
> Version: 3.1.435, BuildTime: 2023-12-18T06:47:45Z
> ```
> 
>  ```
> % ipsw diff /ipsw/Macmin9,1/UniversalMac_14.0_23A344_Restore.ipsw /ipsw/Macmin9,1/UniversalMac_14.1_23B74_Restore.ipsw  -V
> Using config file: /Users/yoda/.config/ipsw/config.yml
>    • Diffing KERNELCACHES
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac13g from UniversalMac_14.0_23A344_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac13j from UniversalMac_14.0_23A344_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac14g from UniversalMac_14.0_23A344_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.mac14j from UniversalMac_14.0_23A344_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache199242566/kernelcache.release.vma2 from UniversalMac_14.0_23A344_Restore.ipsw
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac13g from UniversalMac_14.1_23B74_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac13j from UniversalMac_14.1_23B74_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac14g from UniversalMac_14.1_23B74_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.mac14j from UniversalMac_14.1_23B74_Restore.ipsw
>       • Extracted /var/folders/qb/5d749j6s5751hzqrj_pqc6x80000gn/T/ipsw_extract_kcache271957024/kernelcache.release.vma2 from UniversalMac_14.1_23B74_Restore.ipsw
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>       • Parsing Kernelcache IMG4
>       • Decompressing Kernelcache
>          • Kernelcache is LZFSE compressed
>    • failed to get kext start addresses: section __PRELINK_INFO.__kmod_start not found
>    • failed to get kext start addresses: section __PRELINK_INFO.__kmod_start not found
>    • Diffing DYLD_SHARED_CACHES
>    • Mounting 'Old' SystemOS DMG
>       • Extracted 078-35929-533.dmg from UniversalMac_14.0_23A344_Restore.ipsw
>       • Mounting 078-35929-533.dmg
>    • Mounting 'New' SystemOS DMG
>       • Extracted 097-26443-097.dmg from UniversalMac_14.1_23B74_Restore.ipsw
>       • Mounting 097-26443-097.dmg
>    • Parsing Cache             cache=/tmp/078-35929-533.dmg.mount/System/Library/dyld/dyld_shared_cache_arm64e
>    • Parsing Cache             cache=/tmp/097-26443-097.dmg.mount/System/Library/dyld/dyld_shared_cache_arm64e
>    • Diffing MachOs
>    • Scanning filesystem
>       • Extracted 078-29483-526.dmg from UniversalMac_14.0_23A344_Restore.ipsw
>       • Mounting filesystem 078-29483-526.dmg
>       • Unmounting 078-29483-526.dmg
>       • Unmounting 'Old' SystemOS DMG
>       • Unmounting 'New' SystemOS DMG
>       • Deleting 'Old' SystemOS DMG
>       • Deleting 'New' SystemOS DMG
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104e31378]
> 
> goroutine 1 [running]:
> github.com/blacktop/ipsw/internal/search.scanDmg.func3({0x140650ffb90, 0x67}, {0x0?, 0x0?}, {0x14064e38b40?, 0x5f?})
> 	github.com/blacktop/ipsw/internal/search/search.go:55 +0x28
> path/filepath.walk({0x14064e38b40, 0x5f}, {0x1068c60b0, 0x14001bb9ee0}, 0x140029a5048)
> 	path/filepath/path.go:497 +0x170
> path/filepath.walk({0x14064e389c0, 0x57}, {0x1068c60b0, 0x14001bb9e10}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x14064e388a0, 0x51}, {0x1068c60b0, 0x14001bb9d40}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x1400235b590, 0x49}, {0x1068c60b0, 0x14001bad040}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x1400235ac30, 0x46}, {0x1068c60b0, 0x14001bac5b0}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x1400423c190, 0x42}, {0x1068c60b0, 0x14001b8ed00}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x14002162ec0, 0x3a}, {0x1068c60b0, 0x140008b3ba0}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x14002162e00, 0x35}, {0x1068c60b0, 0x140008b3ad0}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x14066062300, 0x2b}, {0x1068c60b0, 0x14066154b60}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x14004df8270, 0x23}, {0x1068c60b0, 0x14004ddc4e0}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.walk({0x1406478b960, 0x1c}, {0x1068c60b0, 0x14004ddc000}, 0x140029a5048)
> 	path/filepath/path.go:501 +0x1d4
> path/filepath.Walk({0x1406478b960, 0x1c}, 0x14019177048)
> 	path/filepath/path.go:572 +0x6c
> github.com/blacktop/ipsw/internal/search.scanDmg({0x16b9a3912, 0x40}, {0x14019b30780, 0x11}, {0x105fad999, 0xa}, 0x1074dafa0?)
> 	github.com/blacktop/ipsw/internal/search/search.go:54 +0x4d0
> github.com/blacktop/ipsw/internal/search.ForEachMachoInIPSW({0x16b9a3912, 0x40}, 0x140029a9288?)
> 	github.com/blacktop/ipsw/internal/search/search.go:108 +0xcc
> github.com/blacktop/ipsw/internal/commands/macho.DiffIPSW({0x16b9a3912, 0x40}, {0x16b9a3953, 0x3f}, 0x140029a5af0)
> 	github.com/blacktop/ipsw/internal/commands/macho/diff.go:128 +0x10c
> github.com/blacktop/ipsw/internal/diff.(*Diff).parseMachos(...)
> 	github.com/blacktop/ipsw/internal/diff/diff.go:517
> github.com/blacktop/ipsw/internal/diff.(*Diff).Diff(0x1400053aa00)
> 	github.com/blacktop/ipsw/internal/diff/diff.go:197 +0x870
> github.com/blacktop/ipsw/cmd/ipsw/cmd.glob..func9(0x140004a9e00?, {0x140007fd450, 0x2, 0x105f9acc8?})
> 	github.com/blacktop/ipsw/cmd/ipsw/cmd/diff.go:75 +0x348
> github.com/spf13/cobra.(*Command).execute(0x1071d3760, {0x140007fd400, 0x5, 0x5})
> 	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
> github.com/spf13/cobra.(*Command).ExecuteC(0x1071d5fa0)
> 	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
> github.com/spf13/cobra.(*Command).Execute(...)
> 	github.com/spf13/cobra@v1.8.0/command.go:1039
> github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
> 	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:70 +0x24
> main.main()
> 	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x1c
> ```

K, should be fixed in latest release.

**Comment by blacktop** [comment]
Ya, I'll be curious as you start digging in with ghidra what indicators best reflect actual code changes etc (bug fixes specifically). After than detecting new features being added to code would be interesting etc.

**Comment by clearbluejar** [comment]
This feature is here so I will close this issue.👍 

As we research more about the section changes that are important, I will send a new issue for the filter feature.
