### ISSUE TITLE
`ipsw diff` - Extract changed files / Extraction command generation

### ISSUE THREAD

**Issue by clearbluejar** [blacktop/ipsw#372]
Currently a workflow for extracting changed files across two ipsws is this:

1. `% ipsw diff UniversalMac_14.0_23A344_Restore.ipsw UniversalMac_14.1_23B74_Restore.ipsw`
2. Review the diff report.
3. Extract interesting files that have changed manually from dsc from both firmwares by: 
  - `ipsw extract -d UniversalMac_14.0_23A344_Restore.ipsw`
  - `ipsw dyld split dyld_shared_cache_arm64e`
  - dig around for files that have changed. 

It would be nice (I think and this is open to discussion) to have `ipsw` have a subcommand/flag  to either dump all discovered changed files to a folder, or generate the `ipsw` file extraction commands necessary. There is some complexity to extracting the dylibs, as it is a multi stage/command process. It would be easier to generate extract commands for the macho files outside the DSC, if at some point those are available in the diff (#371)  😀

**Comment by blacktop** [comment]
I'll add the ability to dump the 'changed' machos, kexts and dylibs to a JSON output that you could then use via some script to generate the extractions

**Comment by blacktop** [comment]
added `ipsw diff --json` to last release.  you can save JSON when also setting the `--output` flag or it'll send it to stdout which you can filter etc w/ `jq`

Let me know if that works

**Comment by clearbluejar** [comment]
Trying this now.

**Comment by clearbluejar** [comment]
Output looks good. With the results I should be able to get the "updated" paths from each section.  
![image](https://github.com/blacktop/ipsw/assets/3752074/9bf8824f-9693-4204-9a9e-55a340242a9a)

The idea of a [filter](https://github.com/blacktop/ipsw/issues/371#issuecomment-1862891719) is still powerful for being able to only list binaries with data, code, or plist changes.  A future ticket still. 

It might be nice to have specific items for build and version. Something like this: 
![image](https://github.com/blacktop/ipsw/assets/3752074/3307efe7-488d-43d9-a896-6bdc8f64ec53)

Otherwise we could parse it out from the title.

**Comment by blacktop** [comment]
Sounds like this issue has been satisfied
