### ISSUE TITLE
--no-color option doesn't seem to work

### ISSUE THREAD

**Issue by pwmoore** [blacktop/ipsw#387]
### What happened?

I want to pipe `ipsw`'s output through some command line processing. In particular, I'm using the `ipsw dyld search objc` command. 

Since I'm piping the output into other tools, I don't want color. However, the `--no-color` option doesn't seem to turn off color. I also tested it for the `ipsw dyld str` command and the same issue occurred.

### How can we reproduce this?

Use the command `ipsw dyld search objc --no-color -p <PROTOCOL_NAME> /path/to/dyld_shared_cache_arm64e`

### ipsw version

```bash
Built from latest Github source
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
I think I got em' all.  Cutting release now
