### ISSUE TITLE
failed to parse plists in IPSW: failed to parse devicetree when extracting iOS 9 IPSW

### ISSUE THREAD

**Issue by 0x6A62646576** [blacktop/ipsw#389]
### What happened?

```sh
   ⨯ failed to parse plists in IPSW: failed to parse devicetree: failed to parse Img4 DeviceTree: failed to parse Img4 device tree data: unexpected EOF
```

I expected extract not to fail

### How can we reproduce this?

```sh
ipsw download appledb --os iOS --device iPhone6,1 --build 13G36
ipsw extract iPhone6,1_9.3.5_13G36_Restore.ipsw
```

### ipsw version

```bash
Version: 3.1.447, BuildTime: 2024-01-19T02:09:28Z
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
What is the exact `ipsw extract` cmd you are running? I assumpe `-dtree` ?

**Comment by blacktop** [comment]
https://www.theiphonewiki.com/wiki/DeviceTree 

> After iOS 10, almost all the img4 images for 64-bit devices are not encrypted

Most of the files in iOS 9 IPSWs are encrypted. *(I added some better error logging to detect this)*

**Comment by 0x6A62646576** [comment]
I was looking to extract some files from the file system image with `-f -p pattern`. Thanks for updating the error message.
