### ISSUE TITLE
Trying to create a nix package. `no required module provides package github.com/blacktop/ipsw/pkg/sandbox/compile`

### ISSUE THREAD

**Issue by Luxvao** [blacktop/ipsw#390]
### What happened?

I'm trying to create a nix package for ipsw since I saw that it doesn't exist and I like the tool. I have to clarify that I have no experience in go and as such I have no idea what's going wrong. It seems like the `ipsw/pkg/sandbox/compile` doesn't exist. I checked on github and it isn't there. It seems that it's imported in `cmd/ipsw/cmd/sb/sb_cmpl.go`. What is it used for?

### How can we reproduce this?

This issue also happens whenever I run `go mod vendor`.

### ipsw version

```bash
3.1.447
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Luxvao** [comment]
Removing the import fixes the issue. I'd assume it was left in there accidentally?

**Comment by blacktop** [comment]
See https://github.com/blacktop/nur

I've created a NEW NUR for `ipsw` so it'll be auto-updated w/ every release.  Were you going to try and make an official `nix-community/NUR` pkg?

**Comment by blacktop** [comment]
I've also removed the cmd, it wasn't placed there accidentally, but if it's affecting peoples ability to build `ipsw` offline I'll remove it for now.

**Comment by Luxvao** [comment]
What was it actually used for?

**Comment by blacktop** [comment]
closing now, let me know if the NUR nix package has any issues 👍
