### ISSUE TITLE
⨯ failed to mount DMGs: failed to get SystemOS DMG: no SystemOS DMG found: cryptex not found

### ISSUE THREAD

**Issue by F1248** [blacktop/ipsw#393]
### What happened?

```
   • Diffing KERNELCACHES     
      • Extracted /var/folders/n4/r3ygmhy913g608w_shj66cgw0000gn/T/ipsw_extract_kcache825868927/kernelcache.release.n71 from iPhone_4.7_15.8_19H370_Restore.ipsw
      • Parsing Kernelcache IMG4 
      • Decompressing Kernelcache
         • kernelcache is LZSS compressed
         • compressed size: 20791560, uncompressed: 42827776, checkSum: 0x7ac3ac35
      • Extracted /var/folders/n4/r3ygmhy913g608w_shj66cgw0000gn/T/ipsw_extract_kcache2932249997/kernelcache.release.n71 from iPhone_4.7_15.8.1_19H380_Restore.ipsw
      • Parsing Kernelcache IMG4 
      • Decompressing Kernelcache
         • kernelcache is LZSS compressed
         • compressed size: 20791562, uncompressed: 42827776, checkSum: 0x6286ab9f
   • Diffing DYLD_SHARED_CACHES
   • Mounting 'Old' SystemOS DMG
   ⨯ failed to mount DMGs: failed to get SystemOS DMG: no SystemOS DMG found: cryptex not found
```

### How can we reproduce this?

`ipsw diff iPhone_4.7_15.8_19H370_Restore.ipsw iPhone_4.7_15.8.1_19H380_Restore.ipsw --verbose`

- https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-76337/06663E02-EF9F-465C-A958-AA7F3B238C2A/iPhone_4.7_15.8_19H370_Restore.ipsw
- https://updates.cdn-apple.com/2024WinterFCS/fullrestores/052-24002/3C5A4D81-E873-4F65-9511-24D93FE043A6/iPhone_4.7_15.8.1_19H380_Restore.ipsw

### ipsw version

```bash
Version: 3.1.450, BuildTime: 2024-01-25T17:30:01Z
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Additional context

Thank you very much for this tool!

**Comment by blacktop** [comment]
should be fixed in latest release.  please test and close if solved 👍

**Comment by F1248** [comment]
Thank you very much, now it works perfectly!
