### ISSUE TITLE
download latest --black-list will only remove a single item

### ISSUE THREAD

**Issue by h4x4g0n1337** [blacktop/ipsw#4]
the iteration in 'download_latest.go' over --black-list will break when a match is found.
This is false as multiple items should be removed.

While fixing it I changed --black-list to support a list strings delimited with ','

```
diff --git a/cmd/ipsw/cmd/download_latest.go b/cmd/ipsw/cmd/download_latest.go
index 21c460c..c882b7c 100644
--- a/cmd/ipsw/cmd/download_latest.go
+++ b/cmd/ipsw/cmd/download_latest.go
@@ -74,12 +74,22 @@ var latestCmd = &cobra.Command{
 		}
 
 		if len(doNotDownload) > 0 {
-			for i, v := range builds {
-				if strings.Contains(v.Identifier, doNotDownload) {
-					builds = append(builds[:i], builds[i+1:]...)
-					break
+			var validBuilds []api.Build
+			doNot := strings.Split(doNotDownload, ",")
+			for _, v := range builds {
+				valid := true
+
+				for _, doNotDownload = range doNot {
+					if strings.Contains(v.Identifier, doNotDownload) {
+						valid = false
+						break
+					}
+				}
+				if valid {
+					validBuilds = append(validBuilds, v)
 				}
 			}
+			builds = validBuilds
 		}
 
 		log.Debug("URLs to Download:")
```

The following will now work
```
ipsw download -V latest --yes --black-list AppleTV,iPhone
```

**Comment by blacktop** [comment]
I like that, but worry about people trying to blacklist iPhone11,2 for example and then getting unexpected behavior.  I do intend on adding the ability to filter more than AppleTV etc, but not sure how via the cli, maybe requiring it. be surrounded in double quotes? "AppleTV,iPhone11,2" ?

**Comment by h4x4g0n1337** [comment]
You can just use a different delimiter. semi-colon could do the trick (";")

**Comment by blacktop** [comment]
so it seems like the way to do this using the cli library I am using is to have one flag per item in the list.  I have updated it and updated the README, please let me know what you think.  😁

**Comment by blacktop** [comment]
oh I also added a `--white-list` flag as that might be what most people actually want ;)
