### ISSUE TITLE
class-dump: address not within any segment's address range

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [blacktop/ipsw#425]
### What happened?

I'm trying to class-dump the CommerceKit framework, extracted from dyld_shared_cache_x86_64h, and `ipsw` returns an error while trying to process the binary:

```console
% docker run --rm -itv $(pwd):/mnt ghcr.io/blacktop/ipsw:v3.1.462 class-dump /mnt/CommerceKit --headers -o /mnt/out
Usage:
  ipsw class-dump [<DSC> <DYLIB>|<MACHO>] [flags]

Aliases:
  class-dump, cd

Flags:
      --arch string     Which architecture to use for fat/universal MachO
  -a, --cat string      Dump category (regex)
  -c, --class string    Dump class (regex)
      --deps            Dump imported private frameworks
      --headers         Dump ObjC headers
  -h, --help            help for class-dump
  -o, --output string   Folder to write headers to
  -p, --proto string    Dump protocol (regex)
      --re              RE verbosity (with addresses)
      --refs            Dump ObjC references too
      --theme string    Color theme (nord, github, etc) (default "nord")
  -x, --xcfw            🚧 Generate a XCFramework for the dylib

Global Flags:
      --color           colorize output
      --config string   config file (default is $HOME/.config/ipsw/config.yaml)
      --no-color        disable colorize output
  -V, --verbose         verbose output

   ⨯ failed to read objc_class_t at vmaddr 0x201445b44d0: failed to seek to addr 0x201445b44d0: address 0x201445b44d0 not within any segment's adress range
```

### How can we reproduce this?

Run `docker run --rm -itv $(pwd):/mnt ghcr.io/blacktop/ipsw:v3.1.462 class-dump /mnt/CommerceKit --headers -o /mnt/out` within a folder containing the CommerceKit binary. Here follows a copy of the binary:

[CommerceKit.zip](https://github.com/blacktop/ipsw/files/14809827/CommerceKit.zip)

### ipsw version

```console
% docker run --rm -it ghcr.io/blacktop/ipsw:v3.1.462 version                                          
Version: , BuildTime: 20240324
```

### Search

- [x] I did search for other open and closed issues before opening this

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
Looking into it now.  Can I ask where you got that dylib?

`❯ ipsw cd 23E224__Mac15,12/dyld_shared_cache_arm64e CommerceKit`

This does work.

**Comment by blacktop** [comment]
I think this is failing because you extracted

**Comment by t0rr3sp3dr0** [comment]
I extracted it from macOS 14.4 using https://github.com/keith/dyld-shared-cache-extractor. I’ve tried using `ipsw dsc e dyld_shared_cache_x86_64h --all`, but it failed with this:

```console
% docker run --rm -v $(pwd):/mnt -it ghcr.io/blacktop/ipsw:v3.1.462 dsc e /mnt/dyld_shared_cache_x86_64h --all
   • Extracting all dylibs from /mnt/dyld_shared_cache_x86_64h
       1m47s [------------------------------------------------------------------------------| 12/2883 ] 
Usage:
  ipsw dyld extract <DSC> <DYLIB> [flags]

Aliases:
  extract, e

Flags:
  -a, --all             Split ALL dylibs
  -c, --cache string    Path to .a2s addr to sym cache file (speeds up analysis)
      --force           Overwrite existing extracted dylib(s)
  -h, --help            help for extract
      --objc            Add ObjC metadata to extracted dylib(s) symtab
  -o, --output string   Directory to extract the dylib(s)
      --slide           Apply slide info to extracted dylib(s)
      --stubs           Add stub islands to extracted dylib(s) symtab

Global Flags:
      --color           colorize output
      --config string   config file (default is $HOME/.config/ipsw/config.yaml)
      --no-color        disable colorize output
  -V, --verbose         verbose output

   ⨯ failed to parse fixups from in memory MachO: macho does not contain LC_DYLD_CHAINED_FIXUPS
```

**Comment by blacktop** [comment]
I think extracting isn't necessary.  The keith extractor does literally the EXACT same thing as `ipsw dyld split DSC` but that just calls a XCode lib that throws away a lot of information to extract which is why the class-dump fails

**Comment by t0rr3sp3dr0** [comment]
I can confirm both `ipsw cd dyld_shared_cache_x86_64h CommerceKit` and `ipsw dsc e dyld_shared_cache_x86_64h CommerceKit` work. But if I run `ipsw cd CommerceKit` with the dylib that `ipsw` extracted, it fails with the same error as before.

IDA is able to decompile the dylib just fine. So it doesn’t look like it’s getting corrupted on extraction.

**Comment by blacktop** [comment]
https://github.com/blacktop/ipsw/blob/master/cmd/ipsw/cmd/dyld/dyld_extract.go#L128

`ipsw dsc extract` is a hidden cmd and shouldn't show up in `--help` but I haven't removed it from the docs (I should add warnings for people still using it) 

I'll fix it, but am not sure when I'll have time yet

**Comment by t0rr3sp3dr0** [comment]
I was under the impression the dylib would contain all necessary information for class-dump to work. I’ll avoid extracting the dsc moving forward. Thanks!
