### ISSUE TITLE
Print json output from `ipsw download dev`

### ISSUE THREAD

**Issue by CRKatri** [blacktop/ipsw#43]
You have to code to scrape developer.apple.com/download/, if you could make that data available it be parsed separately it would be wonderful. (I really don't want to write auth code)

**Comment by blacktop** [comment]
![will-ferrell-consider-it-done](https://user-images.githubusercontent.com/6118188/140466498-d50eb642-f80f-4880-afbb-96fdba39f587.gif)

**Comment by CRKatri** [comment]
Thank you!
