### ISSUE TITLE
objc class-dump crash

### ISSUE THREAD

**Issue by Rokey1990** [blacktop/ipsw#436]
### What happened?

command:
`ipsw cd bigoshow --headers -o bigoshow-headers`

console error output:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10591de10]

goroutine 1 [running]:
github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).Headers.func1(0x140006e2000)
	github.com/blacktop/ipsw/internal/commands/macho/objc.go:599 +0xe60
github.com/blacktop/ipsw/internal/commands/macho.(*ObjC).Headers(0x140000e7080)
	github.com/blacktop/ipsw/internal/commands/macho/objc.go:646 +0x74
github.com/blacktop/ipsw/cmd/ipsw/cmd.init.func25(0x1400083f000?, {0x14000233000, 0x1, 0x106a26980?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/class_dump.go:223 +0xa90
github.com/spf13/cobra.(*Command).execute(0x107dfe2e0, {0x14000232fc0, 0x4, 0x4})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x107dfe5c0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:67 +0x24
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x1c

### How can we reproduce this?

macho file is private, so sorry cannot attach it.

### ipsw version

```bash
Version: 3.1.469, BuildCommit: d68424c299186d57717ef938e7fd02f7fc0553d1
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
Can you please also provide the binary that crashed `ipsw`?

**Comment by blacktop** [comment]
you could also try building `master` and see if that latest fix fixes it

**Comment by Rokey1990** [comment]
> you could also try building `master` and see if that latest fix fixes it

Great! It works! Thank you very much!
