### ISSUE TITLE
class dump objc categories class name missed for NSObject/UIView etc.

### ISSUE THREAD

**Issue by Rokey1990** [blacktop/ipsw#445]
### What happened?

objc code:
```
@interface NSObject(ExtensionDemo)

- (void)ext_test1;

@end
```

command:
`ipsw cd ReviewToolDemo -a ExtensionDemo`

output:
```
@interface (ExtensionDemo)

/* instance methods */
- (void)ext_test1;

@end
```

the classVMAddr=0, it seems GetBindName from the macho file not works.
![image](https://github.com/blacktop/ipsw/assets/11733468/30eae9b3-3aa0-4c10-9508-0737f0090a1f)

### How can we reproduce this?

[ReviewToolDemo.zip](https://github.com/blacktop/ipsw/files/15023963/ReviewToolDemo.zip)
`ipsw cd ReviewToolDemo -a ExtensionDemo`

### ipsw version

```bash
Version: 3.1.470, BuildCommit: 0f0880bb8ea7688ed5d8afc4254cd5136cfdbd07
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
@t0rr3sp3dr0 ?

**Comment by blacktop** [comment]
fixed in https://github.com/blacktop/go-macho/commit/237bf7151a5bd2a97223ede07fe12bca35f56e66

**Comment by blacktop** [comment]
FYI @Rokey1990 in the future that was an issue in the go-macho pkg

Thank you for letting me know!

**Comment by blacktop** [comment]
@Rokey1990 this should be fixed now

**Comment by blacktop** [comment]
wait, there might be something weird going on w/ a collision of go-macho versions?

**Comment by blacktop** [comment]
I think I somehow accidentally created a tag for this before and it got registered w/ the Go pkgs

So I just created another go-macho release to avoid this collision as I don't know how to remove the prev cached tag in the golang pkg servers etc

**Comment by Rokey1990** [comment]
It does't works well.
I think the GetBindName also has a bug too, the "categoryPtr.ClsVMAddr"  is always 0 for NSObject or UIView(symbols in other dynamic libraries)，this case, GetBindName will return NSObject only, even the real class name is UIView.
```
// GetBindName returns the import name for a given dyld chained pointer
func (f *File) GetBindName(pointer uint64) (string, error)
```
In some documents, they use the address of categoryPtr.ClsVMAddr(ptr + sizeof(uint64)) to get the bind name, Whether we need to do the same? 

my debug image: 
![image](https://github.com/blacktop/ipsw/assets/11733468/fd7b339b-1002-4ab3-bacb-cd802b7e3ba8)
![image](https://github.com/blacktop/ipsw/assets/11733468/8b6cb911-623e-4b66-b8ee-640f7ee2110f)

**Comment by blacktop** [comment]
do you have a specific example in the orig binary you supplied for UIView?

I believe I've fixed the ptr==0 case for category class name lookup

I'll now try and fix it everywhere else it is used

**Comment by blacktop** [comment]
@Rokey1990 please check latest release

**Comment by blacktop** [comment]
I believe I've mostly been testing binaries w/ the NEW chained-fixup binds/rebases so didn't properly test the OLD `LC_DYLD_INFO_ONLY` style as much w/ Objc 

Thank you for reporting!

Please keep these issues coming! and make sure to also test out all the Swift parsers as well 👍

**Comment by Rokey1990** [comment]
Thanks! The latest release has been verifield, it works well👍! 

I'll verify swift parsers later, if any issules found, I'll tell you right away!

**Comment by blacktop** [comment]
This should now be fixed in master (i'll push out a new release soon, just waiting on #451)

I also added a `--demangle` flag to the `class-dump` cmd, but it just does the same thing as using the `-V` flag (meaning -V already swift-demangles the class-dump)

**Comment by Rokey1990** [comment]
Nothing is wrong with master👍! Thank you!
