### ISSUE TITLE
ipsw swift-dump --arch option

### ISSUE THREAD

**Issue by obj-p** [blacktop/ipsw#454]
### What happened?

Providing an arch option is not read by the command. It will still prompt like the following:

```sh
% ipsw swift-dump --arch arm64 /Applications/Xcode.app/Contents/SharedFrameworks/PreviewsXcodeUI.framework/Versions/Current/PreviewsXcodeUI 
? Detected a universal MachO file, please select an architecture to analyze:  [Use arrows to move, type to filter]
> Amd64, x86_64
  AARCH64, ARM64
```

### How can we reproduce this?

```sh
% ipsw swift-dump --arch arm64 /Applications/Xcode.app/Contents/SharedFrameworks/PreviewsXcodeUI.framework/Versions/Current/PreviewsXcodeUI 
? Detected a universal MachO file, please select an architecture to analyze:  [Use arrows to move, type to filter]
> Amd64, x86_64
  AARCH64, ARM64
```

### ipsw version

```bash
% ipsw version
Version: 3.1.475, BuildCommit: b7d163e6730d3db38ffb6b4071e4e2e3ebbc4577
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Could it be due to the "class_dump.arch" string: https://github.com/blacktop/ipsw/blob/b7d163e6730d3db38ffb6b4071e4e2e3ebbc4577/cmd/ipsw/cmd/swift_dump.go#L150

**Comment by blacktop** [comment]
> Could it be due to the "class_dump.arch" string:
> 
> https://github.com/blacktop/ipsw/blob/b7d163e6730d3db38ffb6b4071e4e2e3ebbc4577/cmd/ipsw/cmd/swift_dump.go#L150

Great catch! it was a dump copy-pasta typo error and is fixed in master now.

Thanks!
