### ISSUE TITLE
Feature request: ipsw download rss --download DOWNLOAD_DIR --match REGEX

### ISSUE THREAD

**Issue by doronz88** [blacktop/ipsw#48]
Hi :)

Great work for the newly added RSS feed. I'd like to use it to automate download of newly released versions of iOS and macOS images (and possibly other releases also).
Can you implement a feature to download each product when it's released? I have no problem supplying the required credentials (which I guess are required to download the beta releases)

**Comment by blacktop** [comment]
So I already have the `ipsw download dev --watch` command which sounds like what you are describing. However, in my own practice Apple would sign me out (EVEN though I would refresh my session every 5mins) eventually, breaking my ability to auto-download the betas. 

If you supplied your creds in the configuration file for example (I've also explored store that sensitive info in user's keychains so it's not in plain text anywhere) you'd still get prompted for the 2factor pin code every time you downloaded something. 

This is why currently the `ipsw download rss --watch` just creates a desktop notification alerting the user currently.

**Comment by blacktop** [comment]
Until I can find a way to prevent Apple from logging me out I don't think auto-developer-portal downloads will work.  However, with Apple adding this RSS feed (if it really is :new: and not just new to me) then maybe they are understanding the need to download ASAP and might be open to allowing for much longer or permanent sessions or even... API access to the dev portal !?!?!? 🙏

**Comment by doronz88** [comment]
When I'm downloading through the developer portal I'm not signed out every 5 minutes, so I guess there should be some workarround.

**Comment by blacktop** [comment]
So I wasn't logged out every 5 mins (I refresh the session every 5 mins.)  What would happen is I was start watching for any NEW downloads to show up and walk away from my machine and then come back later that day and see I was logged out at some point.  So I'm not sure when it actually logs you out?  I've also noticed that the "Remember me" checkbox doesn't seem to be respected when signing in via the browser and when I log into the browser it always logs me out over night at some point and I have to log back in. 

Does that not happen for you?

**Comment by doronz88** [comment]
The password is requested again but the two factor isn't

**Comment by blacktop** [comment]
it is... DONE!!!

**Comment by doronz88** [comment]
Dude... wow! 😃
