### ISSUE TITLE
subCacheUUID field should probably be subCachesOffset instead

### ISSUE THREAD

**Issue by mstange** [blacktop/ipsw#49]
https://github.com/blacktop/ipsw/blob/05af7d2bde570035b25e7bfdf316d9f363c0106c/hack/extras/Dyld.bt#L116-L117

It seems like the field before the numSubCaches field is pointing at a list of subcache info structs which has length numSubCaches. The subcache info struct is 24 bytes big, 16 bytes UUID + 8 bytes something else.

This allows you to get the UUID for each subcache.

**Comment by mstange** [comment]
Some evidence from /usr/lib/dsc_extractor.bundle:

<img width="602" alt="Screen Shot 2021-11-07 at 10 37 45 AM" src="https://user-images.githubusercontent.com/961291/140652164-42c80ac8-7416-4dd6-b263-93cf9c381c9f.png">

**Comment by blacktop** [comment]
Yes, it is definitely not a "UUID" I figured that out a month ago here: 

https://github.com/blacktop/ipsw/blob/05af7d2bde570035b25e7bfdf316d9f363c0106c/pkg/dyld/file.go#L151

It appears to be an offset to the end of the `imagesTextOffset` in the subCaches, but in the "primary" cache you are right it seems to point to small amount of data that the subCache's do not contain.  Good find with respects to the UUIDs!

**Comment by blacktop** [comment]
The stuff that I thought looked like bit-field flags after `progClosuresTrieWithSubCachesSize` might tell you what kind of cache it is an how to interpret the *(incorrect)* `subCacheUUID` field perhaps? Or maybe one of these fields:
```
    uint32 unknown8;
    uint32 unknown9;
```

**Comment by blacktop** [comment]
What I was always MOST interested in what the mysterious `unknown10Offset` field.  I see that it's an offset to a struct of what looks like large arrays of offsets?  That might be where the `patchInfo` went.

**Comment by mstange** [comment]
The unknown10Offset field is already present in dyld 852.2, which is public:
https://opensource.apple.com/source/dyld/dyld-852.2/dyld3/shared-cache/dyld_cache_format.h.auto.html

Or are you saying that the existing header definition cannot be used for subcaches, and that the subcaches have other data in those places?

**Comment by mstange** [comment]
Oh, oops, never mind. I got confused because some fields later in the header look very similar to other fields earlier in the header.

**Comment by blacktop** [comment]
So you can tell how the field should be interpreted IF the numSubCaches is greater than 0.  I have updated my 010 template to reflect it.  Thank you for your help!

**Comment by blacktop** [comment]
Also the "8 bytes something else." is the "end offset" of the contamination of the sub caches (so far) or the totalSize.  So for subCache.1 the field is it's `size` and for subCache.2 it's the size of subCache.1 + subCache.2 and so on.

**Comment by mstange** [comment]
Ah, nice. So `cumulativeSize` might be an appropriate name.

**Comment by blacktop** [comment]
Yes! That's perfect.

**Comment by mstange** [comment]
The `cumulativeSize` field is called `cacheVMOffset`: https://github.com/apple-oss-distributions/dyld/blob/5c9192436bb195e7a8fe61f22a229ee3d30d8222/cache-builder/dyld_cache_format.h#L496

**Comment by nipsarejusttittips** [comment]
It has already been updated 👍
