### ISSUE TITLE
fail to class dump

### ISSUE THREAD

**Issue by miku1958** [blacktop/ipsw#491]
### What happened?

⨯ failed to read protocol at pointer 0x10000066fced40 (converted 0x1e6fced40); failed to read class method vmaddr: failed to read methods at vmaddr 0x1e9ccfff0: failed to read method_t name cstring: failed to Seek to address 0x60a5a8b9: address 0x60a5a8b9 not within any mappings address range

### How can we reproduce this?

ipsw class-dump /System/Volumes/Preboot/Cryptexes/OS/System/Library/dyld/dyld_shared_cache_arm64e Foundation

### ipsw version

```bash
Version: 3.1.494, BuildCommit: e6cda2548708727baeab2f70946a8912fad6c516
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
Looks like they changed the objc runtime structures again *(I assume this is macOS 15 beta?)*

**Comment by miku1958** [comment]
> Looks like they changed the objc runtime structures again *(I assume this is macOS 15 beta?)*

No, I am dumping 14.5，and old version can dump it

**Comment by blacktop** [comment]
@t0rr3sp3dr0 please feel ZERO obligation to take a look, but if you had any spare cycles I thought I'd ask 🙏 

I'm currently slammed w/ iOS18/macOS15 beta changes, but will look into this soon.

**Comment by blacktop** [comment]
@miku1958 please try with latest release

**Comment by blacktop** [comment]
@miku1958 I believe it should be fixed now, can you please confirm?
