### ISSUE TITLE
class dump all images

### ISSUE THREAD

**Issue by miku1958** [blacktop/ipsw#493]
### Is your feature request related to a problem? Please describe.

class-dump currently requires image names, but I checked the code and it does allow for 1 parameter and checks all images with only 1 parameter
https://github.com/blacktop/ipsw/blob/a578cd2bda64234e774134551e9d026754bb015f/cmd/ipsw/cmd/class_dump.go#L103C2-L103C19

### Describe the solution you'd like

class dump all image with 1 argument

### Describe alternatives you've considered

N/A

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
adding in latest release 👍
