### ISSUE TITLE
Delta OTA's missed without --build and --version passed  

### ISSUE THREAD

**Issue by nick123pig** [blacktop/ipsw#514]
### What happened?

It seems you need to present `--build` and `--version` to `ipsw download ota` in order to actually get all of the delta OTA's (specifically with delta OTAs). Obviously this isn't a defect of the ipsw tool, rather it's how Pallas determines what to return. I would have figured that passing 17.5 would be sufficient, but I needed to pass all information. 

### How can we reproduce this?

With `--version` and without `--build` (Note 1 result)
```
$ ./ipsw download ota --platform ios --version 17.5 --device iPhone14,7 --delta -j
[{"url":"https://updates.cdn-apple.com/2024SpringFCS/patches/062-02442/975FA2B2-E85E-4AFB-ADA0-B8DD9A85EB51/com_apple_MobileAsset_SoftwareUpdate/0d28c428f6b03c224d55432c0cd0da9e26aeec4d.zip","description":"iOS1751Long","product":"iOS","devices":["iPhone14,7_D27AP"],"version":"17.5.1","build":"21F90","size":"6.2 GB","hash":"29b4635b4792e4960ef96bdaede8676baf421414","hash_algorithm":"SHA-1"}]
```

Without `--version` and with `--build` (Note 1 result)
```
$ ./ipsw download ota --platform ios --device iPhone14,7 --build 21F79  --delta -j
[{"url":"https://updates.cdn-apple.com/2024SpringFCS/patches/062-02442/975FA2B2-E85E-4AFB-ADA0-B8DD9A85EB51/com_apple_MobileAsset_SoftwareUpdate/0d28c428f6b03c224d55432c0cd0da9e26aeec4d.zip","description":"iOS1751Long","product":"iOS","devices":["iPhone14,7_D27AP"],"version":"17.5.1","build":"21F90","size":"6.2 GB","hash":"29b4635b4792e4960ef96bdaede8676baf421414","hash_algorithm":"SHA-1"}]
```

With `--version` and with `--build` (Note 2 results)
```
$ ./ipsw download ota --platform ios --version 17.5 --build 21F79 --device iPhone14,7 --delta -j
[{"url":"https://updates.cdn-apple.com/2024SpringFCS/patches/062-02442/975FA2B2-E85E-4AFB-ADA0-B8DD9A85EB51/com_apple_MobileAsset_SoftwareUpdate/0d28c428f6b03c224d55432c0cd0da9e26aeec4d.zip","description":"iOS1751Long","product":"iOS","devices":["iPhone14,7_D27AP"],"version":"17.5.1","build":"21F90","size":"6.2 GB","hash":"29b4635b4792e4960ef96bdaede8676baf421414","hash_algorithm":"SHA-1"},{"url":"https://updates.cdn-apple.com/2024SpringFCS/patches/052-99125/C103035E-F911-41B0-BA30-E872C7B22E26/com_apple_MobileAsset_SoftwareUpdate/0f80086cbda7c00ba1c5660658d4fb74f86b6538.zip","description":"iOS1751Short","product":"iOS","devices":["iPhone14,7_D27AP"],"version":"17.5.1","build":"21F90","size":"310 MB","hash":"7df68ac47c0eb60740686ad6fc2a34e30e6755d3","hash_algorithm":"SHA-1"}]
```

### ipsw version

```bash
$ ipsw version
Version: 3.1.480, BuildCommit: 2fffe45e5437a6f0ac4527edc4336fb80d853bbb
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

I am willing to pick this issue up, but I would wonder what an acceptable and maintainable solution would be. The options I've considered:
 
- UX: Either Require or Present a warning to the user that it's highly recommended to pass `--build` in order to get all OTA's
- Code: Assuming there is a 1/1 relationship between version and build, perform a lookup in some sort of lookup dictionary and automatically pass the additional info 

Any other guidance?

**Comment by blacktop** [comment]
My instinct is to just at a flag validation check [here](https://github.com/blacktop/ipsw/blob/master/cmd/ipsw/cmd/download/download_ota.go#L169) to let the user know if they use the `--delta` flag they need to set the others (and error out)

**Comment by blacktop** [comment]
I guess the code version would be to "auto-lookup" the version of `--build` and fill that out?  I think I might already do that somewhere? *(and visa versa for the `--version`)

I believe the version/build IS 1-to-1 for a specific `--device` but not in general etc

In the past Apple has had different `version` be 1-to-many to `build`s

**Comment by blacktop** [comment]
I'm not sure how popular the `--delta` flag is?  I usually like `ipsw` to feel as "apple-y"/"magic" as possible for the default/popular use cases.

And MUCH more fine grained and strict around 'power user' niche features etc

**Comment by blacktop** [comment]
this is in the latest release. Thx for reporting! 👍
