### ISSUE TITLE
Getting errors while trying to retrieve key for Mac ipsw or trying to decrypt directly the .dmg.aea file using the key.

### ISSUE THREAD

**Issue by TheiPhoneDev** [blacktop/ipsw#524]
### What happened?

I'm getting errors while trying to retrieve key for Mac ipsw or trying to decrypt directly the .dmg.aea file using the key.

I ran the following command:
1) ipsw fw aea --key-val 'base64:tveg0af9i7LAfo8V663zNhA8JhoR+QTivycbF4AG22E=' 'UniversalMac_15.1_24B5009l_Restore/044-09315-017.dmg.aea' --output /tmp

Error:    ⨯ failed to parse AEA: failed to parse AEA: open UniversalMac_15.1_24B5009l_Restore/044-09315-017.dmg.aea: operation not permitted

The same happens if I try to get the key, I get an error saying that it failed to parse the plist and can't open the ipsw.

### How can we reproduce this?

Firmware I was analyzing: UniversalMac ipsw 15.1 beta
Command I ran: ipsw fw aea --key-val 'base64:tveg0af9i7LAfo8V663zNhA8JhoR+QTivycbF4AG22E=' 'UniversalMac_15.1_24B5009l_Restore/044-09315-017.dmg.aea' --output /tmp

### ipsw version

```bash
UniversalMac 15.1 beta
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
Is this an unzipped directory you are trying to read from? Unzipped where? It seems that `ipsw` can't open that file?

Also what is your main purpose for decrypting?

If it's just to explore I'd recommend:

```bash
ipsw mount fs UniversalMac_15.1_24B5009l_Restore.ipsw
```

or 

```bash
ipsw mount sys UniversalMac_15.1_24B5009l_Restore.ipsw
```

**Comment by TheiPhoneDev** [comment]
The purpose for decrypting it is just exploration. I followed the same instruction like for iOS ipsw but I did not think about mounting it.

**Comment by blacktop** [comment]
too pull out the DMG you can do `ipsw extract --dmg fs IPSW`

then you can try to run the `ipsw fs aea` cmd on it and let me know if it still doesn't work

but the only thing I can think of based on the output you've shown is `ipsw` doesn't have permissions to read the file the way you have extracted it

**Comment by TheiPhoneDev** [comment]
Oh ok, I'll keep you posted!! So after mounting the ipsw I basically decrypt it and then run the fs aea command in order to access files in it ?

**Comment by TheiPhoneDev** [comment]
> to pull out the DMG you can do `ipsw extract --dmg fs IPSW`
> 
> 
> 
> then you can try to run the `ipsw fs aea` cmd on it and let me know if it still doesn't work
> 
> 
> 
> but the only thing I can think of based on the output you've shown is `ipsw` doesn't have permissions to read the file the way you have extracted it

I have tried to mount it but it continues to show error when parsing the IPSW.

**Comment by TheiPhoneDev** [comment]
@blacktop I was able to decrypt it successfully, the error somehow was due to iTerm, because when I ran the commands in the default terminal they worked as expected.

**Comment by blacktop** [comment]
Ya that means you probably aren't allowing iTerm2 to read from certain folders. These settings are in the Privacy & Security section for n the Settings.app

**Comment by blacktop** [comment]
The `ipsw mount` cmd auto decrypts it

**Comment by TheiPhoneDev** [comment]
> Ya that means you probably aren't allowing iTerm2 to read from certain folders. These settings are in the Privacy & Security section for n the Settings.app

Oh Okok, thank you a lot for the help.

**Comment by blacktop** [comment]
no problem! going to close the issue now
