### ISSUE TITLE
ld error when linking with .tbd output of ipsw dyld tbd --private

### ISSUE THREAD

**Issue by PandasAreBears** [blacktop/ipsw#530]
### What happened?

When generating a .tbd stub for any framework dylib, the output causes ld to error due to malformed input. 

An example of the linker error:

```objc
clang -o build/mdm/main build/mdm/main.o -Fsrc/mdm -framework MDMClientLibrary -framework Foundation
ld: tapi error: malformed file
/Users/pab/Projects/Pocs/C/src/mdm/MDMClientLibrary.framework/MDMClientLibrary.tbd:11:26: error: Expected , between entries!
    symbols:          [ +[MDMAccountUtilities _createMissingBearerTokenError],
                         ^
 in '/Users/pab/Projects/Pocs/C/src/mdm/MDMClientLibrary.framework/MDMClientLibrary.tbd'
```

### How can we reproduce this?

I generated the .tbd output using the following command:

```
ipsw dyld tbd 20F66__iPhone15,3/dyld_shared_cache_arm64e MDMClientLibrary --generic --private
```

### ipsw version

```bash
Version: 3.1.532, BuildCommit: a4397c6bfefccb463e2e0510f4fb02c776948bf7
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Thanks for developing this awesome tool! :)

**Comment by blacktop** [comment]
looking into this the `--private` flag doesn't make sense to have for .tbd file generation (and it add bad syms from ld's point of view) so I've removed it

thank you for reporting
