### ISSUE TITLE
Fail to retrieve AEA1 DMG fcs-keys for fs 

### ISSUE THREAD

**Issue by Alumnae** [blacktop/ipsw#562]
### What happened?

Fail to retrieve AEA1 DMG fcs-keys for fs 

### How can we reproduce this?
```bash
C:\Users\Administrator\Downloads\ipsw_3.1.544_windows_x86_64>ipsw dl appledb --os iOS --version "18.0" --rc --device iPhone13,1 --fcs-keys --output "C:\Users\Administrator\Downloads\ipsw_3.1.544_windows_x86_64\tmp" --confirm
   • Querying AppleDB...
      • Git cloning local 'appledb' to C:\Users\Administrator\.config\ipsw\appledb
Enumerating objects: 42630, done.
Counting objects: 100% (42630/42630), done.
Compressing objects: 100% (21156/21156), done.
Total 42630 (delta 25092), reused 35159 (delta 21184), pack-reused 0 (from 0)
   • Parsing remote IPSW       build=22A3354 devices=iPhone13,1 version=18.0
   • Extracting remote AEA1 DMG fcs-keys
      • Created C:\Users\Administrator\Downloads\ipsw_3.1.544_windows_x86_64\tmp\22A3354__iPhone13,1\044-37228-002.dmg.aea.pem
```
### ipsw version

```bash
3.1.544_windows
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Also tried local ipsw
```bash
C:\Users\Administrator\Downloads\ipsw_3.1.544_windows_x86_64>ipsw extract --fcs-key "C:\Users\Administrator\Downloads\iPhone13,1_18.0_22A3354_Restore.ipsw"
   • Extracting AEA1 DMG fcs-keys
      • Created 22A3354__iPhone13,1\044-37228-002.dmg.aea.pem
```

**Comment by Alumnae** [comment]
Successfully extracted .dmg renaming fs with sys

ipsw fw aea --pem "22A3354__iPhone13,1\044-37228-002.dmg.aea.pem" "22A3354__iPhone13,1\044-37315-002.dmg.aea" --output "C:\Users\Administrator\Downloads\ipsw_3.1.544_windows_x86_64\tmp"

**Comment by blacktop** [comment]
I don't understand what the issue is. You've just shown a bunch of commands working.

**Comment by blacktop** [comment]
I think the misunderstanding is that the fs and the sys fcs key are the same so you don't need to grab both of them. please feel free to re-open if I am wrong
