### ISSUE TITLE
ipsw extract --dmg is missing "exc" option

### ISSUE THREAD

**Issue by mduran80** [blacktop/ipsw#565]
### What happened?

The extract.DMG method supports extracting the "exc" DMG, however the option is not supported in the CLI cmd: 

```golang
if !utils.StrSliceHas([]string{"app", "sys", "fs"}, viper.GetString("extract.dmg")) {
         return fmt.Errorf("invalid DMG type '%s' (must be: app, sys or fs)", viper.GetString("extract.dmg"))
}
```

### How can we reproduce this?

Run "ipsw extract --dmg exc <ipsw>", output will be:

```bash
⨯ invalid DMG type 'exc' (must be: app, sys or fs)
```

### ipsw version

```bash
Version: 3.1.544, BuildCommit: bcbcb14f89eecd90ed9322b8c7b62773e04b2cbb
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
thank you for letting me know!

**Comment by blacktop** [comment]
pushed in latest release
