### ISSUE TITLE
ipsw dyld split dyld_shared_cache_arm64e failed

### ISSUE THREAD

**Issue by AIBUSHISHOU** [blacktop/ipsw#571]
### What happened?

Hey! I tried to use the "ipsw dyld split xxxx" command to extract the system symbols for iOS 18.0 (22A3354)，then I encountered an error:
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/3fe32425-52ed-4641-88c1-4fb20482ffaf">

### How can we reproduce this?

1. Download xxx.ipsw file from https://updates.cdn-apple.com/2024FallFCS/fullrestores/062-77819/DBD19B90-6CA3-44A2-A4EA-D4BD1E89578F/iPhone13,2,iPhone13,3_18.0_22A3354_Restore.ipsw
2. Use ipsw extract --dyld xxx.ipsw file, then you'll get a directory named "22A3354__iPhone13,3"
3. cd 22A3354__iPhone13,3
4. Use  ipsw dyld split dyld_shared_cache_arm64e -o "18.0 (22A3354) arm64e/Symbols"

### ipsw version

```bash
Version: 3.1.544, BuildCommit: bcbcb14f89eecd90ed9322b8c7b62773e04b2cbb
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

macOS version: 15.0
Xcode version: latest

**Comment by blacktop** [comment]
Do you have XCode installed or downloaded?

**Comment by AIBUSHISHOU** [comment]
> Do you have XCode installed or downloaded?

<img width="392" alt="image" src="https://github.com/user-attachments/assets/80995dc1-a052-4046-b622-b91079cd09ba">
Yes, I have installed XCode, and updated it to the lastest version.

**Comment by AIBUSHISHOU** [comment]
> Do you have XCode installed or downloaded?

I just use "-x" to specify the path of XCode, and it works! Thank you for your reply!

**Comment by JakeBrown2000** [comment]
For what its worth I was having this issue and I believe the issue is if you downloaded Xcode command line tools before downloading Xcode then `xcode-select --print-path` points to the command line tools instead of `Xcode.app`, running `sudo xcode-select --reset` should update Xcode-select to point towards `/Applications/Xcode.app/Contents/Developer` which means you shouldn't need to use -x from now on.
