### ISSUE TITLE
Add a `--no-symbolicate` option to `ipsw dsc disass`

### ISSUE THREAD

**Issue by doronz88** [blacktop/ipsw#574]
### Is your feature request related to a problem? Please describe.

Nope

### Describe the solution you'd like

When providing the `--no-symbolicate` option to `ipsw dsc disass`, just output the disassembley without the need to symbolicate the whole DSC prior.

### Describe alternatives you've considered

No idea

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
have you tried `--quiet` ?  It's also MUCH faster 😉
