### ISSUE TITLE
Feature request: dyld macho --extract --create-symtab

### ISSUE THREAD

**Issue by doronz88** [blacktop/ipsw#58]
Reversing dylibs from the DSC can be tiresome. Each dylib references another, and without loading each one's dependencies you get an image with too many invalid pointers.
I think `ipsw` could create a `.symtab` section where every extracted image has references to all the rest of the exported symbols from the other dylibs. That way, We could reverse only one image with all its required dependencies without loading each one individually.

If this works well, I'll also attempt writing an IDA plugin to load modules from the iOS 15 DSC based on `ipsw`.

**Comment by blacktop** [comment]
https://user-images.githubusercontent.com/6118188/213362089-24d6b6d0-27b4-4358-80c4-04f5b97a651e.mp4

**Comment by blacktop** [comment]
`ipsw dyld extract DSC DYLIB --slide --objc --stubs` will add `--imports` soon as well

**Comment by doronz88** [comment]
Wow! Thanks! 😃
