### ISSUE TITLE
downloading an iOS 18+ simulator fails

### ISSUE THREAD

**Issue by xvolks** [blacktop/ipsw#583]
### What happened?

Downloading an iOS Simulator for iOS 18 always fails, the same command for iOS 17 works, tho.

### How can we reproduce this?

```
$ echo 'iOS 18.0 Simulator' | ./main download xcode --sim
? Select what to download: iOS 18.0 Simulator Runtime
   • Downloading iOS 18.0 Simulator Runtime...
   ⨯ failed to download file: Get "": unsupported protocol scheme ""
```   

### ipsw version

```bash
Both:
from master commit e362f83c6

and from brew:

$ ipsw version                                                                                                                                        2481ms  Jeu 24 oct 07:57:13 2024
Version: 3.1.550, BuildCommit: 9311653620081767a93392ac8081e2359d2816bd
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

the `dl.Source` value is empty in `download_xcode.go` since I suspect the `GetDVTDownloadableIndex()` did not populate the structure.
The URL is still on the same pattern (needs login [iOS_18_Simulator_Runtime.dmg](https://download.developer.apple.com/Developer_Tools/iOS_18_Simulator_Runtime/iOS_18_Simulator_Runtime.dmg))

**Comment by blacktop** [comment]
you know that's an illegal **hidden** cmd that no one is supposed to know about rrrrrright?!

**Comment by blacktop** [comment]
I'm going to let you off with a warning this time... but you BETTER not tell anyone about this cmd or next time... 🚓 👮 straight to jail
