### ISSUE TITLE
 unknown flag: --fcs-key

### ISSUE THREAD

**Issue by Echoooo0827** [blacktop/ipsw#586]
### What happened?

When I run ipsw extract --fcs-key Apple_Vision_Pro_2 1_22N5 81_Restore ipsw in window10, the unknown flag: --fcs-key appears, I am executing according to the command of the official website
![image](https://github.com/user-attachments/assets/c0c8f2eb-024f-4f88-b9bc-fa63a41e8c9a)
![image](https://github.com/user-attachments/assets/6b094e56-2cce-4b83-ab01-47ca283a744c)
How can I solve it? Please help to answer, thank you！

### How can we reproduce this?

System：window10
Cmd：ipsw extract --fcs-key Apple_Vision_Pro_2.1_22N5 81_Restore.ipsw

### ipsw version

```bash
ipsw version: 3.1.199
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
3.1.199 is a VERY old version of `ipsw` the latest version is 3.1.556 (that flag was added much later than the version you are running on Windows)

**Comment by Echoooo0827** [comment]
thank you



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 15, 2024 02:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [blacktop/ipsw]  unknown flag: --fcs-key (Issue #586)




 
3.1.199 is a VERY old version of ipsw the latest version is 3.1.556 (that flag was added much later than the version you are running on Windows)
