### ISSUE TITLE
ipsw extract failed on linux

### ISSUE THREAD

**Issue by tamwei** [blacktop/ipsw#591]
### What happened?

I run this cmd `snap run ipsw extract --dyld "iPhone15,4_17.6.1_21G93_Restore.ipsw" -o "./" > /dev/null`   failed on  linux.

But this cmd `ipsw extract --dyld "iPhone15,4_17.6.1_21G93_Restore.ipsw" -o "./" > /dev/null `   works well on Mac.

### How can we reproduce this?

step 1, download ipsw
  `snap run ipsw download ipsw --device iPhone15,4 --build 21G93`
step 2, extract ipsw
 `snap run ipsw extract --dyld "iPhone15,4_17.6.1_21G93_Restore.ipsw" -o "./" > /dev/null`

if step2 succeed, I will continue step3
 `snap run ipsw split --dyld "dyld_shared_cache_arm64e" -o "./splited" > /dev/null`

### ipsw version

```bash
ipsw Version: 3.1.556, BuildCommit: 847083943511132e212517b04085a5b35e3cabca
os version: Linux version 3.10.0-1160.31.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Thu Jun 10 13:32:12 UTC 2021
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment]
on linux apfs-fuse is required to extract the DSC from the IPSW, you can see an example of how to install it here: https://github.com/blacktop/ipsw/blob/d2ce6380558575a4bfd4296d0bd3e6fbcc7aa32e/Dockerfile#L30

**Comment by tamwei** [comment]
oh, thank you.

But `ipsw dyld split` can not run on linux(https://github.com/blacktop/ipsw/issues/296), it seems I can not extract the binary images from a ipsw on linux.

**Comment by blacktop** [comment]
that is correct, that cmd shouldn't even be compiled into the linux binaries as it requires XCode to be installed (which is macOS only)

There is a hidden cmd `ipsw dyld extract` that will work on linux, but the reason it is hidden is it can create split dylib machos that are subtly incorrect (w/ bad segment/section boundaries etc) so it's output shouldn't be trusted but in some circumstances is good enough for general RE (until I get around to fixing it)
