### ISSUE TITLE
Win10 not working - cannot access the file because another process has locked a portion of the file.

### ISSUE THREAD

**Issue by xcloudx01** [blacktop/ipsw#6]
Hi, the tool is unable to download any firmware. Each attempt i try, it gives the following error and makes a 0kb file:
"failed to download file: write iPadPro_9.7_13.1.3_17A878_Restore.ipsw.download: The process cannot access the file because another process has locked a portion of the file."

I don't have any antiviruses running, so i', not sure what process could be blocking it. I tried running it as admin but still no luck. Any ideas? Cheers.

**Comment by blacktop** [comment]
are you using the latest version of ipsw.exe ?

**Comment by xcloudx01** [comment]
yeah im using the latest windows build thats in the releases section

**Comment by blacktop** [comment]
I disabled the file locking and it works now, however, if two people are downloading to the same folder the second might try and "continue" the first's download.  I will add a fix for that by adding a prompt asking if the second should try and continue or not.

**Comment by blacktop** [comment]
Added, please let me know if it still does not work.  

FYI, I also added a new cmd to download betas

```bash
ipsw.exe download beta 17C5046a
```
