### ISSUE TITLE
__OBJC_RO doesn't exist

### ISSUE THREAD

**Issue by turnerrocks1** [blacktop/ipsw#60]
bootywarrior@Bootys-MacBook-Air ~ % /Users/bootywarrior/Downloads/ipsw_3.1.19_macOS_arm64/ipsw symbolicate /Users/bootywarrior/Desktop/web.ips /Users/bootywarrior/Downloads/dyld_shared_cache_arm64
  - No selectors.
Error: failed to parse objc selectors: segment __OBJC_RO does not exist
Usage:
  ipsw symbolicate <crashlog> <dyld_shared_cache> [flags]

Flags:
  -d, --demangle   Demangle symbol names
  -h, --help       help for symbolicate
  -u, --unslide    Unslide the crashlog for easier static analysis

Global Flags:
      --config string   config file (default is $HOME/.ipsw.yaml)
  -V, --verbose         verbose output

   ⨯ failed to parse objc selectors: segment __OBJC_RO does not exist

To help you further based off our last interaction when I had an issue on windows.
This isn't a cache off the ipsw it's from the iOS Device itself this time it's for the iPhone8,1 running 12.1.4 (16D57) dyld_shared_cache from "/System/Library/caches/com.apple.dyld"

**Comment by turnerrocks1** [comment]
tested with version 3.1.19 and 3.1.29

**Comment by blacktop** [comment]
Again, many thanks for letting me know about this! I worry a lot of people use `ipsw` and when they hit one of these bugs they just give up.  I'm very grateful for you letting me know!  I just pushed a 🆕 release that should hopefully fix this issue.

**Comment by turnerrocks1** [comment]
No problem this is Twitter handle @turnerhackz1 I like this product a lot and find it very useful so no problem
