### ISSUE TITLE
ipsw extract with ios 18+ failed

### ISSUE THREAD

**Issue by dearestman** [blacktop/ipsw#604]
### What happened?

Hello!
my macOs version Ventura 13.7 and device Macbook Pro 16 2021 (M1 Pro)
 
I'm extracting dyld_shared_cache on ios 18+ and have this error:

and have this error:

• Extracting dyld_shared_cache
1.50 GiB / 1.50 GiB [==========================================================| ✅ ] 1.03 MiB/s
• Mounting DMG /var/folders/z6/1wdyd33d73g3fml19z20pgdxwr7jqs/T/ipsw_extract_remote_dyld330086142/044-37624-002.dmg.aea
Usage:
ipsw extract <IPSW/OTA | URL> [flags]

Aliases:
extract, e, ex

Flags:
—device string Device to extract kernel for (e.g. iPhone10,6)
—dmg string Extract DMG file (app, sys, fs)
—driverkit Extract DriverKit dyld_shared_cache
—dtree Extract DeviceTree
-d, —dyld Extract dyld_shared_cache
-a, —dyld-arch stringArray dyld_shared_cache architecture to extract
-x, —exclave Extract Exclave Bundle
—fcs-key Extract AEA1 DMG fcs-key pem files
-f, —files Extract File System files
—flat Do NOT perserve directory structure when extracting
-h, —help help for extract
—iboot Extract iBoot
—insecure do not verify ssl certs
-j, —json Output extracted paths as JSON
—kbag Extract Im4p Keybags
-k, —kernel Extract kernelcache
-o, —output string Folder to extract files to
-p, —pattern string Extract files that match regex
—pem-db string AEA pem DB JSON file
—proxy string HTTP/HTTPS proxy
-r, —remote Extract from URL
—sep Extract sep-firmware
—sptm Extract SPTM and TXM Firmwares
—sys-ver Extract SystemVersion

Global Flags:
—color colorize output
—config string config file (default is $HOME/.config/ipsw/config.yaml)
—no-color disable colorize output
-V, —verbose verbose output

⨯ failed to IPSW FS dmg: failed to mount /var/folders/z6/1wdyd33d73g3fml19z20pgdxwr7jqs/T/ipsw_extract_remote_dyld330086142/044-37624-002.dmg.aea: exit status 1: hdiutil: attach failed - образ не распознан

### How can we reproduce this?

./ipsw extract -d -r https://updates.cdn-apple.com/2024FallFCS/fullrestores/062-77756/9AA40CC8-01BD-4430-9F67-6016EF20A592/iPhone12,1_18.0_22A3354_Restore.ipsw -o ./output

### ipsw version

```bash
i'm using binary file with last version (v3.1.558)
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dearestman** [comment]
it is work with ios 16,17

**Comment by malwr4n6** [comment]
I am facing the same error message for extracting dyld shared cache for macos 15.2 stable ipsw 
 ⨯ failed to extract 044-80992-001.dmg.aea from IPSW: open 044-80992-001.dmg.aea: permission denied

**Comment by blacktop** [comment]
@malwr4n6  is this on the same IPSW as @dearestman  ?

**Comment by malwr4n6** [comment]
@blacktop it's a different one. I faced the same error on 15.2 macos IPSW

**Comment by blacktop** [comment]
fixed in last commit. thank you for letting me know! 👍
