### ISSUE TITLE
Can we get the watch fimware ? 

### ISSUE THREAD

**Issue by truonggiang0710** [blacktop/ipsw#63]
Hi team,

Can we get the watch firmware ?

**Comment by blacktop** [comment]
ipsw or OTA?

**Comment by truonggiang0710** [comment]
Ipsw please !

**Comment by truonggiang0710** [comment]
Hi team, 
Can we download ipsw or OTA  firmare ? 
How to do it ?

**Comment by blacktop** [comment]
### OTA
```bash
❯ ipsw download ota --device Watch5,4 --model N146bAP -V --platform watchos
```

**Comment by blacktop** [comment]
To download ipsw firmware you need a developer account:

```bash
❯ ipsw download dev
```

**Comment by truonggiang0710** [comment]
Thanks @blacktop .

**Comment by truonggiang0710** [comment]
> To download ipsw firmware you need a developer account:
> 
> ```shell
> ❯ ipsw download dev
> ```

How to download the  ipsw watch. Because I enter dev account, and I don't see any watch firmware here.

**Comment by blacktop** [comment]
My apologies, I forgot that Apple doesn't post the Watch IPSWs anywhere and on the dev portal they just have the beta profile available.  However, the iphonewiki seems to have them so they MUST be available somewhere?  If you find out where please let me know and I will added it to `ipsw`

**Comment by truonggiang0710** [comment]
I find out 8.1 firmware available at https://www.theiphonewiki.com/wiki/Firmware/Apple_Watch/8.x
The 8.1 firmware was unsigned by Apple. The latest firmware is 8.3, I need to find out it.
Do you know how to create ipsw from the OTA zip file ? Or how to restore watch by OTA zip file?

**Comment by blacktop** [comment]
My tool's primarily purpose is to be a research tool. 

It seems that the way the iPhone wiki guys get those IPSWs is that they are posted on Twitter by shadowy figures;)

So I guess your best bet it to try and find them on Twitter?

I won't be able to add Watch IPSWs to my tool in an automated way unfortunately as there doesn't seem to be an official way to get them from Apple.

**Comment by truonggiang0710** [comment]
Thanks @blacktop

**Comment by blacktop** [comment]
There's not a lot of IPSWs on the WIKI but you can get them now with:
```bash
❯ ipsw download wiki --device Watch6,9 -V
   • URLs to download:
      • https://updates.cdn-apple.com/2021FallFCS/fullrestores/071-99434/9B52ADA2-3E27-4E68-93EF-D3555E3D5B26/Watch6,9_8.0_19R346_Restore.ipsw
      • https://updates.cdn-apple.com/2021FCSFall/fullrestores/002-12850/16820EE6-A501-4583-A7D9-F151F93530BE/Watch6,9_8.0.1_19R354_Restore.ipsw
      • https://updates.cdn-apple.com/2021FCSFall/fullrestores/071-65932/1F21232C-1FCA-4573-A94E-F2E3DFF470DF/Watch6,9_8.1_19R570_Restore.ipsw
      • https://updates.cdn-apple.com/2022SpringFCS/fullrestores/002-61353/96577C33-63D0-4CA9-9F20-2DB9594DB392/Watch6,9_8.4.1_19S550_Restore.ipsw
? You are about to download 4 ipsw files. Continue? (y/N)
```

**Comment by truonggiang0710** [comment]
Thanks @blacktop . But they are not the latest version.
