### ISSUE TITLE
Kernelcache does not contain LINKINFO.__

### ISSUE THREAD

**Issue by turnerrocks1** [blacktop/ipsw#66]
This is an old-style A9 kernelcache (Darwin Kernel Version 18.2.0: Wed Dec 19 20:28:52 PST 2018; root:xnu-4903.242.2~1/RELEASE_ARM64_S8000)
<img width="1440" alt="Screen Shot 2021-12-29 at 4 30 08 PM" src="https://user-images.githubusercontent.com/23098599/147708307-9c3440b3-abd6-429c-9ad3-51dd56b2f029.png">

Straight from the "/System/Library/caches/com.apple.kernelcaches"

This is what the segment names are when decompiled

**Comment by turnerrocks1** [comment]
oops forgot the command line : "
bootywarrior@Bootys-MacBook-Air Desktop % /Users/bootywarrior/Downloads/ipsw_3.1.32_macOS_arm64/ipsw kernel symbolsets kernel.decrypted 
   ⨯ kernelcache does NOT contain __LINKINFO.__symbolsets
"

**Comment by blacktop** [comment]
So I'm not even sure what symbolsets ARE.  They just showed up I think in iOS14 so I thought I'd parse them in case anyone cared? 🤷 So that older kernelcache might have a `__LINKINFO` segment but NOT a `__symbolsets` in that segment.

**Comment by blacktop** [comment]
FYI, you can also get the kernel's segments by running:
```bash
> ipsw macho info /System/Library/caches/com.apple.kernelcaches/kernelcache_arm64e
```
