### ISSUE TITLE
issues on BVX compress

### ISSUE THREAD

**Issue by NineSecurityPro** [blacktop/ipsw#7]
iOS 13.2 using bvx compress, good news is that ipsw still can decompress it, but the decompressed kernel can not parsed as kernel cache by IDA

**Comment by blacktop** [comment]
Can you point me to the hw name or IPSW you were using so I can test with it?

**Comment by blacktop** [comment]
It seems like what data is actually there is:
```bash
kernelcache.release.iphone12b.decompressed: Mach-O universal binary with 1 architecture: [arm64e:Mach-O 64-bit executable arm64e]
kernelcache.release.iphone12b.decompressed (for architecture arm64e):   Mach-O 64-bit executable arm64e
```
jtool2 -dec gives:
```bash
/tmp/kernel: Mach-O 64-bit executable arm64e
```

**Comment by blacktop** [comment]
So it is just wrapped in a universal machO?  I guess I could strip that away like jtool2 does?

**Comment by blacktop** [comment]
Fixed in last commit, please let me know if that didn't do the trick
