### ISSUE TITLE
ipsw version shows blank string, consequently update command errors

### ISSUE THREAD

**Issue by wangoland** [blacktop/ipsw#70]
Latest release for linux (v3.1.45)
When running: 'ipsw version' the following is output:
```
dan@ubuntu-test:~/Downloads/ipsw$ ./ipsw version
Version:   , BuildTime: 
```

This then results in the 'ipsw update' command fails with the following error:
```
dan@ubuntu-test:~/Downloads/ipsw$ ./ipsw update
Error: Malformed version: 
Usage:
  ipsw update [flags]

Flags:
      --detect            detect my platform
  -h, --help              help for update
      --insecure          do not verify ssl certs
  -p, --platform string   ipsw platform binary to update
      --proxy string      HTTP/HTTPS proxy
      --replace           overwrite current ipsw

Global Flags:
      --config string   config file (default is $HOME/.ipsw.yaml)
  -V, --verbose         verbose output

   ⨯ Malformed version:       
```

Checking the latest pipeline for building the following error is displayed:
![image](https://user-images.githubusercontent.com/9201149/150107664-b0f91606-9719-406c-839e-869091541f3b.png)

If you re-run the same echo command with the "--insecure" flag set it can successfully obtain the latest iOS version from Apple:
```
dan@ubuntu-test:~/Downloads/ipsw$ echo ::set-output name=version::$(LD_LIBRARY_PATH=/usr/local/lib ./ipsw download ipsw --show-latest --insecure)
::set-output name=version::15.2.1
```

**Comment by blacktop** [comment]
I've noticed sometimes cert stuff can fail on CI/CD servers, however, in the most recent Actions Go run, the update cmd succeeds.

I can tell from your examples that you are running a locally built version of `./ipsw` the BuildDate and Version info is set/injected at build time as can be seen here: https://github.com/blacktop/ipsw/blob/master/Makefile#L55

you can run `make build` to build a local instance of `ipsw` and it should have those fields defined (but you will have to also run `make dev-deps` first to install `svu` which I believe will only work in a `git clone` and not a downloaded ZIP if that makes sense.

**Comment by blacktop** [comment]
Oh and the `ipsw update` cmd needs to have the Version defined to check against a newer version, so that makes sense that it would fail.

**Comment by wangoland** [comment]
Hi. I'm not using a locally built version I'm using the release version from the releases page (running from the tar.gz file).

**Comment by blacktop** [comment]
Which OS/arch?

**Comment by wangoland** [comment]
Ubuntu Linux 20.04.3 LTS

**Comment by blacktop** [comment]
My apologies for not understanding your issue before.  I believe I have fixed it in the latest release.  Can you please test and if it is fixed close the issue?

Thank you for reporting! ❤️

**Comment by wangoland** [comment]
Not a problem! And you have done indeed 😄 Thank you for getting that sorted and coming back to me.

Cheers!
