### ISSUE TITLE
Downloading latest IPSW for devices that cant install iOS 13

### ISSUE THREAD

**Issue by danferret** [blacktop/ipsw#8]
The "latest" command only attempts to download the current version of iOS 13, even when specifying a device such as iPad Air which can only install 12.4.3 currently.

Is there a way to automate downloading the latest supported version per device?

**Comment by blacktop** [comment]
I can see why you would want that/expect that to be the apps behavior.  I'll look into it soon.

**Comment by blacktop** [comment]
I have fixed it and will roll out a new release soon.  Please let me know if this doesn't fix it for you.  Thank you for pointing this out to me.
