### ISSUE TITLE
Feature Request: Mach-O signer

### ISSUE THREAD

**Issue by CRKatri** [blacktop/ipsw#82]
The ability to sign binaries is in `jtool2` and would be very useful in `ipsw` too.

**Comment by blacktop** [comment]
I like where your head's at! 🤘

**Comment by CRKatri** [comment]
Also, more importantly, the `jtool2 -vv --sig` command. This is very useful when inspecting a signature.

**Comment by blacktop** [comment]
dude... I thought we were cool... 😢 

```bash
ipsw macho info MACHO --sig -V
```

**Comment by CRKatri** [comment]
I feel stupid 🤦🏻‍♂️, next time I'll read the docs before commenting.

**Comment by blacktop** [comment]
It's cool, I make all these awesome features for my beloved community and don't do a good job advertising them, which is probably why I see people recreating features from `ipsw` all the time 😞 , it's also my fault for writing it in Go I suppose 😉

**Comment by CRKatri** [comment]
Well trust me, they do not go unappreciated (pun not intended). I'll make sure to read the docs more thoroughly in the future 😆. You have so many awesome features in here sometime I lose track of what you already have.

**Comment by blacktop** [comment]
Just to update you on this initial feature request, I'm hopefully going to take another, 🤞  final, attempt at making a "near perfect" dsc splitter, which requires a LOT of macho re-writing, so once I get into that "flow" I should be able to add custom signatures etc.

**Comment by CRKatri** [comment]
Could you extend `ipsw macho info --sig` to work on a `.app` bundle directly? i.e. `ipsw macho info --sig -V TestApp.app` instead of `ipsw macho info --sig -V TestApp.app/TestApp`

**Comment by blacktop** [comment]
> Could you extend `ipsw macho info --sig` to work on a `.app` bundle directly? i.e. `ipsw macho info --sig -V TestApp.app` instead of `ipsw macho info --sig -V TestApp.app/TestApp`

done

**Comment by CRKatri** [comment]
I think the correct way is to actually first check if `path.app/Info.plist` exists, if it does then get the name of the executable from the `CFBundleExecutable` key and read `path.app/CFBundleExecutableVal` if `path.app/Info.plist` doesn't exist, then read `path.app/Contents/Info.plist` and read `path.app/Contents/MacOS/CFBundleExecutableVal`

**Comment by blacktop** [comment]
ah interesting, that does make sense, I checked a handful of apps and they all worked, but that is a much better solution.

**Comment by blacktop** [comment]
Not saying I will or that it makes sense to, but if I re-wrote `ipsw` do you think Swift of Rust would be better?

**Comment by CRKatri** [comment]
Swift definitely. I am not a fan of rust, it is incredibly slow to compile and makes huge binaries. It's package manager is also not very good in my opinion. But personally I think `ipsw` is perfectly fine in Go, I plan on learning go in the future so hopefully I can help you out then.

**Comment by CRKatri** [comment]
> ah interesting, that does make sense, I checked a handful of apps and they all worked, but that is a much better solution.

The current solution will work for most macOS apps. However it won't work for iOS apps.

**Comment by blacktop** [comment]
Is there a comprehensive list of fields for those two plists anywhere?  I figure there might be other interesting fields that I could start mining etc, for example: `CFBundleURLSchemes` 🤔

**Comment by CRKatri** [comment]
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html seems to list some stuff.

**Comment by blacktop** [comment]
should be good now (wrt .apps) 🤞

**Comment by blacktop** [comment]
😏
