### ISSUE TITLE
Split manpages into a seperate pages for each subcommand.

### ISSUE THREAD

**Issue by CRKatri** [blacktop/ipsw#93]
Having a 821 line long manpage (`ipsw man | mandoc | col -b | wc -l`) is not practical for feature discoverability. I think they should be split into different manpages for each subcommand. Ie `ipsw-dyld(1)`, `ipsw-macho(1)`, etc.

**Comment by blacktop** [comment]
I saw that the base cli lib does support breaking it out into MANY sub-man pages, does this work?

**Comment by CRKatri** [comment]
Yes, that is much better, thank you!
