### ISSUE TITLE
Downloading latest ipsw for Macmini9,1 fails

### ISSUE THREAD

**Issue by dimitarnestorov** [blacktop/ipsw#95]
When running `ipsw download ipsw --device Macmini9,1 --latest` I get the following:

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/blacktop/ipsw/internal/download.(*ITunesVersionMaster).GetLatestBuilds(0x1014f2140?, {0x16f52779e, 0xa})
	github.com/blacktop/ipsw/internal/download/itunes.go:158 +0x654
github.com/blacktop/ipsw/cmd/ipsw/cmd.glob..func8(0x101d1b5e0?, {0x101251ccf?, 0x3?, 0x3?})
	github.com/blacktop/ipsw/cmd/ipsw/cmd/download_ipsw.go:181 +0xa08
github.com/spf13/cobra.(*Command).execute(0x101d1b5e0, {0x14000410c00, 0x3, 0x3})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x101d237e0)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/blacktop/ipsw/cmd/ipsw/cmd.Execute()
	github.com/blacktop/ipsw/cmd/ipsw/cmd/root.go:57 +0x2c
main.main()
	github.com/blacktop/ipsw/cmd/ipsw/main.go:27 +0x20
```	

Specifying the version manually works

Version:  3.1.90

**Comment by blacktop** [comment]
Thank you for pointing that out, it is a silly bug on my behalf.

This however, does work, but I'll try and fix it and maybe get rid of the need for the `--macos` flag

``bash
❯ ipsw download ipsw --device Macmini9,1 --macos --latest
```

**Comment by blacktop** [comment]
should be fixed now

**Comment by dimitarnestorov** [comment]
Yes, it's fixed! Thank you!

By the way, it's unable to download ipsw's for the new Mac Studio:
<img width="891" alt="Screen Shot 2022-03-30 at 10 13 38 AM" src="https://user-images.githubusercontent.com/8790386/160773197-7630b282-a8bb-45bb-9763-cc4302566833.png">

Should I open a new issue?

**Comment by blacktop** [comment]
oh man! So the initial reason this was failing is that a macOS IPSW supports ALL M1 hardware, meaning the IPSW is the SAME for all devices, that's why I didn't consider adding `--device` support.  I have an internal DB of devices and which OS they run, but I have to manually update that to keep it in sync.  So I'm now thinking maybe adding `--device` support was a mistake and should instead direct the user to just use the `--macos` flag? 

```bash
ipsw download ipsw --macos --latest
```

What do you think?

**Comment by blacktop** [comment]
I pushed an update that should fix the issue, but in the future you can just skip the --device flag 👍

**Comment by dimitarnestorov** [comment]
> So I'm now thinking maybe adding --device support was a mistake and should instead direct the user to just use the --macos flag?

Removing `--device` for macOS would introduce a breaking change. `--device SomeMacModel0,0` is the same as `--macOS`, so I wouldn't bother. If you're thinking about creating a new major release soon, fine. But keep in mind that Apple may decide to ship different IPSWs for different Macs one day. I would automate a check for that when the internal db is being updated which raises an alert or causes a crash.

> I have to manually update that to keep it in sync

A GitHub Action with a schedule should get rid of the manual burden. You can make it open PRs instead of directly committing to master so you can verify the changes.

> I pushed an update that should fix the issue

Tested it, works fine! Thank you!

P.S. I would suggest beautifying and sorting the internal db JSON file so that when looking at the changes in the commit history it's easy to see what got updated.
